[
  {
    "command": "pip install pennylane",
    "success": true,
    "stdout": "Looking in indexes: https://repo.huaweicloud.com/repository/pypi/simple/\nCollecting pennylane\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/e8/0c/de1e32c368f16eb03eae5e066d37259aa53c950fd7e0b8d788d2ecf75396/pennylane-0.42.1-py3-none-any.whl (4.8 MB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 11.4 MB/s  0:00:00\nRequirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from pennylane) (1.15.3)\nRequirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from pennylane) (2.8.8)\nRequirement already satisfied: rustworkx>=0.14.0 in /usr/local/lib/python3.10/dist-packages (from pennylane) (0.15.1)\nRequirement already satisfied: autograd in /usr/local/lib/python3.10/dist-packages (from pennylane) (1.8.0)\nRequirement already satisfied: appdirs in /usr/local/lib/python3.10/dist-packages (from pennylane) (1.4.4)\nRequirement already satisfied: autoray>=0.6.11 in /usr/local/lib/python3.10/dist-packages (from pennylane) (0.7.2)\nRequirement already satisfied: cachetools in /usr/local/lib/python3.10/dist-packages (from pennylane) (5.3.3)\nCollecting pennylane-lightning>=0.42 (from pennylane)\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/d0/24/e95792186daccb6b5e7f65c58c523471e3fb10b87c4ebcfe901e6e284cee/pennylane_lightning-0.42.0-cp310-cp310-manylinux_2_28_x86_64.whl (2.6 MB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 9.2 MB/s  0:00:00\nRequirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from pennylane) (2.31.0)\nRequirement already satisfied: tomlkit in /usr/local/lib/python3.10/dist-packages (from pennylane) (0.13.3)\nRequirement already satisfied: typing_extensions in /usr/local/lib/python3.10/dist-packages (from pennylane) (4.14.1)\nRequirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from pennylane) (25.0)\nRequirement already satisfied: diastatic-malt in /usr/local/lib/python3.10/dist-packages (from pennylane) (2.15.2)\nRequirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from pennylane) (1.26.4)\nCollecting scipy-openblas32>=0.3.26 (from pennylane-lightning>=0.42->pennylane)\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/01/78/4a113ac866d2cb8190564387050f1402e25d5b9b926111f12d8dd3f9e354/scipy_openblas32-0.3.30.0.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.6 MB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.6/8.6 MB 5.3 MB/s  0:00:01\nRequirement already satisfied: astunparse in /usr/local/lib/python3.10/dist-packages (from diastatic-malt->pennylane) (1.6.3)\nRequirement already satisfied: gast in /usr/local/lib/python3.10/dist-packages (from diastatic-malt->pennylane) (0.6.0)\nRequirement already satisfied: termcolor in /usr/local/lib/python3.10/dist-packages (from diastatic-malt->pennylane) (3.1.0)\nRequirement already satisfied: wheel<1.0,>=0.23.0 in /usr/lib/python3/dist-packages (from astunparse->diastatic-malt->pennylane) (0.37.1)\nRequirement already satisfied: six<2.0,>=1.6.1 in /usr/local/lib/python3.10/dist-packages (from astunparse->diastatic-malt->pennylane) (1.17.0)\nRequirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->pennylane) (3.4.2)\nRequirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->pennylane) (3.10)\nRequirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->pennylane) (2.5.0)\nRequirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->pennylane) (2025.8.3)\nInstalling collected packages: scipy-openblas32, pennylane-lightning, pennylane\n\nSuccessfully installed pennylane-0.42.1 pennylane-lightning-0.42.0 scipy-openblas32-0.3.30.0.2\n",
    "stderr": "WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.\n",
    "execution_time": 10.604616403579712
  }
]