[
  {
    "command": "pip install mako",
    "success": true,
    "stdout": "Looking in indexes: https://repo.huaweicloud.com/repository/pypi/simple/\nCollecting mako\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/87/fb/99f81ac72ae23375f22b7afdb7642aba97c00a713c217124420147681a2f/mako-1.3.10-py3-none-any.whl (78 kB)\nCollecting MarkupSafe>=0.9.2 (from mako)\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/22/35/137da042dfb4720b638d2937c38a9c2df83fe32d20e8c8f3185dbfef05f7/MarkupSafe-3.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (20 kB)\nInstalling collected packages: MarkupSafe, mako\n\nSuccessfully installed MarkupSafe-3.0.2 mako-1.3.10\n",
    "stderr": "WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.\n",
    "execution_time": 1.127445936203003
  },
  {
    "command": "pytest",
    "success": false,
    "stdout": "============================= test session starts ==============================\nplatform linux -- Python 3.10.12, pytest-8.4.1, pluggy-1.6.0\nrootdir: /app/repo_to_process\nconfigfile: pyproject.toml\ncollected 0 items / 7 errors\n\n==================================== ERRORS ====================================\n___________________ ERROR collecting test/test_algorithm.py ____________________\n/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py:512: in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/_pytest/python.py:240: in pytest_pycollect_makeitem\n    return list(collector._genfunctions(name, obj))\n/usr/local/lib/python3.10/dist-packages/_pytest/python.py:466: in _genfunctions\n    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))\n/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py:573: in call_extra\n    return self._hookexec(self.name, hookimpls, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:785: in pytest_generate_tests_for_pyopencl\n    arg_values, ids = get_pyopencl_fixture_arg_values()\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:744: in get_pyopencl_fixture_arg_values\n    for platform, devices in get_test_platforms_and_devices():\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:708: in get_test_platforms_and_devices\n    for platform in cl.get_platforms()]\nE   pyopencl._cl.LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR\n_____________________ ERROR collecting test/test_array.py ______________________\n/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py:512: in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/_pytest/python.py:240: in pytest_pycollect_makeitem\n    return list(collector._genfunctions(name, obj))\n/usr/local/lib/python3.10/dist-packages/_pytest/python.py:466: in _genfunctions\n    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))\n/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py:573: in call_extra\n    return self._hookexec(self.name, hookimpls, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:785: in pytest_generate_tests_for_pyopencl\n    arg_values, ids = get_pyopencl_fixture_arg_values()\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:744: in get_pyopencl_fixture_arg_values\n    for platform, devices in get_test_platforms_and_devices():\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:708: in get_test_platforms_and_devices\n    for platform in cl.get_platforms()]\nE   pyopencl._cl.LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR\n_______________ ERROR collecting test/test_arrays_in_structs.py ________________\n/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py:512: in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/_pytest/python.py:240: in pytest_pycollect_makeitem\n    return list(collector._genfunctions(name, obj))\n/usr/local/lib/python3.10/dist-packages/_pytest/python.py:466: in _genfunctions\n    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))\n/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py:573: in call_extra\n    return self._hookexec(self.name, hookimpls, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:785: in pytest_generate_tests_for_pyopencl\n    arg_values, ids = get_pyopencl_fixture_arg_values()\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:744: in get_pyopencl_fixture_arg_values\n    for platform, devices in get_test_platforms_and_devices():\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:708: in get_test_platforms_and_devices\n    for platform in cl.get_platforms()]\nE   pyopencl._cl.LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR\n_____________________ ERROR collecting test/test_clmath.py _____________________\n/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py:512: in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/_pytest/python.py:240: in pytest_pycollect_makeitem\n    return list(collector._genfunctions(name, obj))\n/usr/local/lib/python3.10/dist-packages/_pytest/python.py:466: in _genfunctions\n    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))\n/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py:573: in call_extra\n    return self._hookexec(self.name, hookimpls, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:785: in pytest_generate_tests_for_pyopencl\n    arg_values, ids = get_pyopencl_fixture_arg_values()\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:744: in get_pyopencl_fixture_arg_values\n    for platform, devices in get_test_platforms_and_devices():\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:708: in get_test_platforms_and_devices\n    for platform in cl.get_platforms()]\nE   pyopencl._cl.LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR\n____________________ ERROR collecting test/test_clrandom.py ____________________\n/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py:512: in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/_pytest/python.py:240: in pytest_pycollect_makeitem\n    return list(collector._genfunctions(name, obj))\n/usr/local/lib/python3.10/dist-packages/_pytest/python.py:466: in _genfunctions\n    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))\n/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py:573: in call_extra\n    return self._hookexec(self.name, hookimpls, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:785: in pytest_generate_tests_for_pyopencl\n    arg_values, ids = get_pyopencl_fixture_arg_values()\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:744: in get_pyopencl_fixture_arg_values\n    for platform, devices in get_test_platforms_and_devices():\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:708: in get_test_platforms_and_devices\n    for platform in cl.get_platforms()]\nE   pyopencl._cl.LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR\n__________________ ERROR collecting test/test_enqueue_copy.py __________________\n/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py:512: in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/_pytest/python.py:240: in pytest_pycollect_makeitem\n    return list(collector._genfunctions(name, obj))\n/usr/local/lib/python3.10/dist-packages/_pytest/python.py:466: in _genfunctions\n    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))\n/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py:573: in call_extra\n    return self._hookexec(self.name, hookimpls, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:785: in pytest_generate_tests_for_pyopencl\n    arg_values, ids = get_pyopencl_fixture_arg_values()\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:744: in get_pyopencl_fixture_arg_values\n    for platform, devices in get_test_platforms_and_devices():\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:708: in get_test_platforms_and_devices\n    for platform in cl.get_platforms()]\nE   pyopencl._cl.LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR\n____________________ ERROR collecting test/test_wrapper.py _____________________\n/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py:512: in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/_pytest/python.py:240: in pytest_pycollect_makeitem\n    return list(collector._genfunctions(name, obj))\n/usr/local/lib/python3.10/dist-packages/_pytest/python.py:466: in _genfunctions\n    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))\n/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py:573: in call_extra\n    return self._hookexec(self.name, hookimpls, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:785: in pytest_generate_tests_for_pyopencl\n    arg_values, ids = get_pyopencl_fixture_arg_values()\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:744: in get_pyopencl_fixture_arg_values\n    for platform, devices in get_test_platforms_and_devices():\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:708: in get_test_platforms_and_devices\n    for platform in cl.get_platforms()]\nE   pyopencl._cl.LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR\n=========================== short test summary info ============================\nERROR test/test_algorithm.py - pyopencl._cl.LogicError: clGetPlatformIDs fail...\nERROR test/test_array.py - pyopencl._cl.LogicError: clGetPlatformIDs failed: ...\nERROR test/test_arrays_in_structs.py - pyopencl._cl.LogicError: clGetPlatform...\nERROR test/test_clmath.py - pyopencl._cl.LogicError: clGetPlatformIDs failed:...\nERROR test/test_clrandom.py - pyopencl._cl.LogicError: clGetPlatformIDs faile...\nERROR test/test_enqueue_copy.py - pyopencl._cl.LogicError: clGetPlatformIDs f...\nERROR test/test_wrapper.py - pyopencl._cl.LogicError: clGetPlatformIDs failed...\n!!!!!!!!!!!!!!!!!!! Interrupted: 7 errors during collection !!!!!!!!!!!!!!!!!!!!\n============================== 7 errors in 0.83s ===============================\n",
    "stderr": "",
    "execution_time": 1.0494086742401123
  }
]