[
  {
    "command": "pip install pocl",
    "success": false,
    "stdout": "Looking in indexes: https://repo.huaweicloud.com/repository/pypi/simple/\n",
    "stderr": "ERROR: Could not find a version that satisfies the requirement pocl (from versions: none)\nERROR: No matching distribution found for pocl\n",
    "execution_time": 1.1906769275665283
  },
  {
    "command": "pytest",
    "success": false,
    "stdout": "============================= test session starts ==============================\nplatform linux -- Python 3.10.12, pytest-8.4.1, pluggy-1.6.0\nrootdir: /app/repo_to_process\nconfigfile: pyproject.toml\ncollected 0 items / 7 errors\n\n==================================== ERRORS ====================================\n___________________ ERROR collecting test/test_algorithm.py ____________________\n/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py:512: in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/_pytest/python.py:240: in pytest_pycollect_makeitem\n    return list(collector._genfunctions(name, obj))\n/usr/local/lib/python3.10/dist-packages/_pytest/python.py:466: in _genfunctions\n    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))\n/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py:573: in call_extra\n    return self._hookexec(self.name, hookimpls, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:785: in pytest_generate_tests_for_pyopencl\n    arg_values, ids = get_pyopencl_fixture_arg_values()\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:744: in get_pyopencl_fixture_arg_values\n    for platform, devices in get_test_platforms_and_devices():\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:708: in get_test_platforms_and_devices\n    for platform in cl.get_platforms()]\nE   pyopencl._cl.LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR\n_____________________ ERROR collecting test/test_array.py ______________________\n/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py:512: in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/_pytest/python.py:240: in pytest_pycollect_makeitem\n    return list(collector._genfunctions(name, obj))\n/usr/local/lib/python3.10/dist-packages/_pytest/python.py:466: in _genfunctions\n    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))\n/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py:573: in call_extra\n    return self._hookexec(self.name, hookimpls, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:785: in pytest_generate_tests_for_pyopencl\n    arg_values, ids = get_pyopencl_fixture_arg_values()\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:744: in get_pyopencl_fixture_arg_values\n    for platform, devices in get_test_platforms_and_devices():\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:708: in get_test_platforms_and_devices\n    for platform in cl.get_platforms()]\nE   pyopencl._cl.LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR\n_______________ ERROR collecting test/test_arrays_in_structs.py ________________\n/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py:512: in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/_pytest/python.py:240: in pytest_pycollect_makeitem\n    return list(collector._genfunctions(name, obj))\n/usr/local/lib/python3.10/dist-packages/_pytest/python.py:466: in _genfunctions\n    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))\n/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py:573: in call_extra\n    return self._hookexec(self.name, hookimpls, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:785: in pytest_generate_tests_for_pyopencl\n    arg_values, ids = get_pyopencl_fixture_arg_values()\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:744: in get_pyopencl_fixture_arg_values\n    for platform, devices in get_test_platforms_and_devices():\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:708: in get_test_platforms_and_devices\n    for platform in cl.get_platforms()]\nE   pyopencl._cl.LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR\n_____________________ ERROR collecting test/test_clmath.py _____________________\n/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py:512: in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/_pytest/python.py:240: in pytest_pycollect_makeitem\n    return list(collector._genfunctions(name, obj))\n/usr/local/lib/python3.10/dist-packages/_pytest/python.py:466: in _genfunctions\n    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))\n/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py:573: in call_extra\n    return self._hookexec(self.name, hookimpls, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:785: in pytest_generate_tests_for_pyopencl\n    arg_values, ids = get_pyopencl_fixture_arg_values()\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:744: in get_pyopencl_fixture_arg_values\n    for platform, devices in get_test_platforms_and_devices():\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:708: in get_test_platforms_and_devices\n    for platform in cl.get_platforms()]\nE   pyopencl._cl.LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR\n____________________ ERROR collecting test/test_clrandom.py ____________________\n/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py:512: in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/_pytest/python.py:240: in pytest_pycollect_makeitem\n    return list(collector._genfunctions(name, obj))\n/usr/local/lib/python3.10/dist-packages/_pytest/python.py:466: in _genfunctions\n    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))\n/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py:573: in call_extra\n    return self._hookexec(self.name, hookimpls, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:785: in pytest_generate_tests_for_pyopencl\n    arg_values, ids = get_pyopencl_fixture_arg_values()\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:744: in get_pyopencl_fixture_arg_values\n    for platform, devices in get_test_platforms_and_devices():\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:708: in get_test_platforms_and_devices\n    for platform in cl.get_platforms()]\nE   pyopencl._cl.LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR\n__________________ ERROR collecting test/test_enqueue_copy.py __________________\n/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py:512: in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/_pytest/python.py:240: in pytest_pycollect_makeitem\n    return list(collector._genfunctions(name, obj))\n/usr/local/lib/python3.10/dist-packages/_pytest/python.py:466: in _genfunctions\n    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))\n/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py:573: in call_extra\n    return self._hookexec(self.name, hookimpls, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:785: in pytest_generate_tests_for_pyopencl\n    arg_values, ids = get_pyopencl_fixture_arg_values()\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:744: in get_pyopencl_fixture_arg_values\n    for platform, devices in get_test_platforms_and_devices():\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:708: in get_test_platforms_and_devices\n    for platform in cl.get_platforms()]\nE   pyopencl._cl.LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR\n____________________ ERROR collecting test/test_wrapper.py _____________________\n/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py:512: in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/_pytest/python.py:240: in pytest_pycollect_makeitem\n    return list(collector._genfunctions(name, obj))\n/usr/local/lib/python3.10/dist-packages/_pytest/python.py:466: in _genfunctions\n    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))\n/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py:573: in call_extra\n    return self._hookexec(self.name, hookimpls, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:785: in pytest_generate_tests_for_pyopencl\n    arg_values, ids = get_pyopencl_fixture_arg_values()\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:744: in get_pyopencl_fixture_arg_values\n    for platform, devices in get_test_platforms_and_devices():\n/usr/local/lib/python3.10/dist-packages/pyopencl/tools.py:708: in get_test_platforms_and_devices\n    for platform in cl.get_platforms()]\nE   pyopencl._cl.LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR\n=========================== short test summary info ============================\nERROR test/test_algorithm.py - pyopencl._cl.LogicError: clGetPlatformIDs fail...\nERROR test/test_array.py - pyopencl._cl.LogicError: clGetPlatformIDs failed: ...\nERROR test/test_arrays_in_structs.py - pyopencl._cl.LogicError: clGetPlatform...\nERROR test/test_clmath.py - pyopencl._cl.LogicError: clGetPlatformIDs failed:...\nERROR test/test_clrandom.py - pyopencl._cl.LogicError: clGetPlatformIDs faile...\nERROR test/test_enqueue_copy.py - pyopencl._cl.LogicError: clGetPlatformIDs f...\nERROR test/test_wrapper.py - pyopencl._cl.LogicError: clGetPlatformIDs failed...\n!!!!!!!!!!!!!!!!!!! Interrupted: 7 errors during collection !!!!!!!!!!!!!!!!!!!!\n============================== 7 errors in 0.81s ===============================\n",
    "stderr": "",
    "execution_time": 1.0578718185424805
  }
]