[
  {
    "command": "pip install -r requirements.txt",
    "success": true,
    "stdout": "Looking in indexes: https://repo.huaweicloud.com/repository/pypi/simple/\nRequirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 1)) (2.2.6)\n",
    "stderr": "WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.\n",
    "execution_time": 0.7505245208740234
  },
  {
    "command": "pip install -r tests-requirements.txt",
    "success": true,
    "stdout": "Looking in indexes: https://repo.huaweicloud.com/repository/pypi/simple/\nCollecting matplotlib (from -r tests-requirements.txt (line 1))\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/ac/64/8d0c8937dee86c286625bddb1902efacc3e22f2b619f5b5a8df29fe5217b/matplotlib-3.10.5-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.7 MB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 14.0 MB/s  0:00:00\nRequirement already satisfied: pip in /usr/local/lib/python3.10/dist-packages (from -r tests-requirements.txt (line 2)) (25.2)\nCollecting coveralls (from -r tests-requirements.txt (line 3))\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/63/e5/6708c75e2a4cfca929302d4d9b53b862c6dc65bd75e6933ea3d20016d41d/coveralls-4.0.1-py3-none-any.whl (13 kB)\nCollecting pytest<=8.1.1 (from -r tests-requirements.txt (line 4))\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/4d/7e/c79cecfdb6aa85c6c2e3cf63afc56d0f165f24f5c66c03c695c4d9b84756/pytest-8.1.1-py3-none-any.whl (337 kB)\nCollecting scipy (from -r tests-requirements.txt (line 5))\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/8e/6d/41991e503e51fc1134502694c5fa7a1671501a17ffa12716a4a9151af3df/scipy-1.15.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (37.7 MB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.7/37.7 MB 14.3 MB/s  0:00:02\nCollecting pillow (from -r tests-requirements.txt (line 6))\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/f0/16/1a6bf01fb622fb9cf5c91683823f073f053005c849b1f52ed613afcf8dae/pillow-11.3.0-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.6 MB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 14.4 MB/s  0:00:00\nRequirement already satisfied: iniconfig in /usr/local/lib/python3.10/dist-packages (from pytest<=8.1.1->-r tests-requirements.txt (line 4)) (2.1.0)\nRequirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from pytest<=8.1.1->-r tests-requirements.txt (line 4)) (25.0)\nRequirement already satisfied: pluggy<2.0,>=1.4 in /usr/local/lib/python3.10/dist-packages (from pytest<=8.1.1->-r tests-requirements.txt (line 4)) (1.6.0)\nRequirement already satisfied: exceptiongroup>=1.0.0rc8 in /usr/local/lib/python3.10/dist-packages (from pytest<=8.1.1->-r tests-requirements.txt (line 4)) (1.3.0)\nRequirement already satisfied: tomli>=1 in /usr/local/lib/python3.10/dist-packages (from pytest<=8.1.1->-r tests-requirements.txt (line 4)) (2.2.1)\nCollecting contourpy>=1.0.1 (from matplotlib->-r tests-requirements.txt (line 1))\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/32/5c/1ee32d1c7956923202f00cf8d2a14a62ed7517bdc0ee1e55301227fc273c/contourpy-1.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (325 kB)\nCollecting cycler>=0.10 (from matplotlib->-r tests-requirements.txt (line 1))\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/e7/05/c19819d5e3d95294a6f5947fb9b9629efb316b96de511b418c53d245aae6/cycler-0.12.1-py3-none-any.whl (8.3 kB)\nCollecting fonttools>=4.22.0 (from matplotlib->-r tests-requirements.txt (line 1))\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/05/57/767e31e48861045d89691128bd81fd4c62b62150f9a17a666f731ce4f197/fonttools-4.59.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.8 MB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 13.4 MB/s  0:00:00\nCollecting kiwisolver>=1.3.1 (from matplotlib->-r tests-requirements.txt (line 1))\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/de/c6/7b9bb8044e150d4d1558423a1568e4f227193662a02231064e3824f37e0a/kiwisolver-1.4.8-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 12.9 MB/s  0:00:00\nRequirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.10/dist-packages (from matplotlib->-r tests-requirements.txt (line 1)) (2.2.6)\nCollecting pyparsing>=2.3.1 (from matplotlib->-r tests-requirements.txt (line 1))\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/05/e7/df2285f3d08fee213f2d041540fa4fc9ca6c2d44cf36d3a035bf2a8d2bcc/pyparsing-3.2.3-py3-none-any.whl (111 kB)\nRequirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib->-r tests-requirements.txt (line 1)) (2.9.0.post0)\nCollecting coverage!=6.0.*,!=6.1,!=6.1.1,<8.0,>=5.0 (from coverage[toml]!=6.0.*,!=6.1,!=6.1.1,<8.0,>=5.0->coveralls->-r tests-requirements.txt (line 3))\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/b9/8e/5a8835fb0122a2e2a108bf3527931693c4625fdc4d953950a480b9625852/coverage-7.10.2-cp310-cp310-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (243 kB)\nCollecting docopt<0.7.0,>=0.6.1 (from coveralls->-r tests-requirements.txt (line 3))\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz (25 kB)\n  Preparing metadata (setup.py): started\n  Preparing metadata (setup.py): finished with status 'done'\nRequirement already satisfied: requests<3.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from coveralls->-r tests-requirements.txt (line 3)) (2.32.4)\nRequirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=1.0.0->coveralls->-r tests-requirements.txt (line 3)) (3.4.2)\nRequirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=1.0.0->coveralls->-r tests-requirements.txt (line 3)) (3.10)\nRequirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=1.0.0->coveralls->-r tests-requirements.txt (line 3)) (2.5.0)\nRequirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=1.0.0->coveralls->-r tests-requirements.txt (line 3)) (2025.8.3)\nRequirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from exceptiongroup>=1.0.0rc8->pytest<=8.1.1->-r tests-requirements.txt (line 4)) (4.14.1)\nRequirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib->-r tests-requirements.txt (line 1)) (1.17.0)\nBuilding wheels for collected packages: docopt\n  Building wheel for docopt (setup.py): started\n  Building wheel for docopt (setup.py): finished with status 'done'\n  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13723 sha256=18d3f3d58c35264d7bb45741f10352b9f2031e235de73f1266d19d85cb2a411b\n  Stored in directory: /root/.cache/pip/wheels/a5/23/1b/9838850321bd67c470dc69d7c0cc326f11b51464583d5cebe6\nSuccessfully built docopt\nInstalling collected packages: docopt, scipy, pyparsing, pillow, kiwisolver, fonttools, cycler, coverage, contourpy, pytest, matplotlib, coveralls\n  Attempting uninstall: pytest\n    Found existing installation: pytest 8.4.1\n    Uninstalling pytest-8.4.1:\n      Successfully uninstalled pytest-8.4.1\n\nSuccessfully installed contourpy-1.3.2 coverage-7.10.2 coveralls-4.0.1 cycler-0.12.1 docopt-0.6.2 fonttools-4.59.0 kiwisolver-1.4.8 matplotlib-3.10.5 pillow-11.3.0 pyparsing-3.2.3 pytest-8.1.1 scipy-1.15.3\n",
    "stderr": "  DEPRECATION: Building 'docopt' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'docopt'. Discussion can be found at https://github.com/pypa/pip/issues/6334\nWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.\n",
    "execution_time": 15.567269802093506
  },
  {
    "command": "pip install -r readthedocs-requirements.txt",
    "success": true,
    "stdout": "Looking in indexes: https://repo.huaweicloud.com/repository/pypi/simple/\nRequirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from -r readthedocs-requirements.txt (line 1)) (2.2.6)\nCollecting numpydoc (from -r readthedocs-requirements.txt (line 2))\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/26/62/5783d8924fca72529defb2c7dbe2070d49224d2dba03a85b20b37adb24d8/numpydoc-1.9.0-py3-none-any.whl (64 kB)\nRequirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from -r readthedocs-requirements.txt (line 3)) (3.10.5)\nCollecting sphinx<7,>=4.2 (from -r readthedocs-requirements.txt (line 4))\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/5f/d8/45ba6097c39ba44d9f0e1462fb232e13ca4ddb5aea93a385dcfa964687da/sphinx-6.2.1-py3-none-any.whl (3.0 MB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 9.9 MB/s  0:00:00\nCollecting sphinxcontrib-applehelp (from sphinx<7,>=4.2->-r readthedocs-requirements.txt (line 4))\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/5d/85/9ebeae2f76e9e77b952f4b274c27238156eae7979c5421fba91a28f4970d/sphinxcontrib_applehelp-2.0.0-py3-none-any.whl (119 kB)\nCollecting sphinxcontrib-devhelp (from sphinx<7,>=4.2->-r readthedocs-requirements.txt (line 4))\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/35/7a/987e583882f985fe4d7323774889ec58049171828b58c2217e7f79cdf44e/sphinxcontrib_devhelp-2.0.0-py3-none-any.whl (82 kB)\nCollecting sphinxcontrib-jsmath (from sphinx<7,>=4.2->-r readthedocs-requirements.txt (line 4))\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/c2/42/4c8646762ee83602e3fb3fbe774c2fac12f317deb0b5dbeeedd2d3ba4b77/sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl (5.1 kB)\nCollecting sphinxcontrib-htmlhelp>=2.0.0 (from sphinx<7,>=4.2->-r readthedocs-requirements.txt (line 4))\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/0a/7b/18a8c0bcec9182c05a0b3ec2a776bba4ead82750a55ff798e8d406dae604/sphinxcontrib_htmlhelp-2.1.0-py3-none-any.whl (98 kB)\nCollecting sphinxcontrib-serializinghtml>=1.1.5 (from sphinx<7,>=4.2->-r readthedocs-requirements.txt (line 4))\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/52/a7/d2782e4e3f77c8450f727ba74a8f12756d5ba823d81b941f1b04da9d033a/sphinxcontrib_serializinghtml-2.0.0-py3-none-any.whl (92 kB)\nCollecting sphinxcontrib-qthelp (from sphinx<7,>=4.2->-r readthedocs-requirements.txt (line 4))\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/27/83/859ecdd180cacc13b1f7e857abf8582a64552ea7a061057a6c716e790fce/sphinxcontrib_qthelp-2.0.0-py3-none-any.whl (88 kB)\nCollecting Jinja2>=3.0 (from sphinx<7,>=4.2->-r readthedocs-requirements.txt (line 4))\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/62/a1/3d680cbfd5f4b8f15abc1d571870c5fc3e594bb582bc3b64ea099db13e56/jinja2-3.1.6-py3-none-any.whl (134 kB)\nRequirement already satisfied: Pygments>=2.13 in /usr/local/lib/python3.10/dist-packages (from sphinx<7,>=4.2->-r readthedocs-requirements.txt (line 4)) (2.19.2)\nCollecting docutils<0.20,>=0.18.1 (from sphinx<7,>=4.2->-r readthedocs-requirements.txt (line 4))\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/93/69/e391bd51bc08ed9141ecd899a0ddb61ab6465309f1eb470905c0c8868081/docutils-0.19-py3-none-any.whl (570 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 570.5/570.5 kB 6.8 MB/s  0:00:00\nCollecting snowballstemmer>=2.0 (from sphinx<7,>=4.2->-r readthedocs-requirements.txt (line 4))\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/c8/78/3565d011c61f5a43488987ee32b6f3f656e7f107ac2782dd57bdd7d91d9a/snowballstemmer-3.0.1-py3-none-any.whl (103 kB)\nCollecting babel>=2.9 (from sphinx<7,>=4.2->-r readthedocs-requirements.txt (line 4))\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/b7/b8/3fe70c75fe32afc4bb507f75563d39bc5642255d1d94f1f23604725780bf/babel-2.17.0-py3-none-any.whl (10.2 MB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 13.6 MB/s  0:00:00\nCollecting alabaster<0.8,>=0.7 (from sphinx<7,>=4.2->-r readthedocs-requirements.txt (line 4))\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/32/34/d4e1c02d3bee589efb5dfa17f88ea08bdb3e3eac12bc475462aec52ed223/alabaster-0.7.16-py3-none-any.whl (13 kB)\nCollecting imagesize>=1.3 (from sphinx<7,>=4.2->-r readthedocs-requirements.txt (line 4))\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/ff/62/85c4c919272577931d407be5ba5d71c20f0b616d31a0befe0ae45bb79abd/imagesize-1.4.1-py2.py3-none-any.whl (8.8 kB)\nRequirement already satisfied: requests>=2.25.0 in /usr/local/lib/python3.10/dist-packages (from sphinx<7,>=4.2->-r readthedocs-requirements.txt (line 4)) (2.32.4)\nRequirement already satisfied: packaging>=21.0 in /usr/local/lib/python3.10/dist-packages (from sphinx<7,>=4.2->-r readthedocs-requirements.txt (line 4)) (25.0)\nRequirement already satisfied: tomli>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from numpydoc->-r readthedocs-requirements.txt (line 2)) (2.2.1)\nRequirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->-r readthedocs-requirements.txt (line 3)) (1.3.2)\nRequirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->-r readthedocs-requirements.txt (line 3)) (0.12.1)\nRequirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->-r readthedocs-requirements.txt (line 3)) (4.59.0)\nRequirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->-r readthedocs-requirements.txt (line 3)) (1.4.8)\nRequirement already satisfied: pillow>=8 in /usr/local/lib/python3.10/dist-packages (from matplotlib->-r readthedocs-requirements.txt (line 3)) (11.3.0)\nRequirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->-r readthedocs-requirements.txt (line 3)) (3.2.3)\nRequirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib->-r readthedocs-requirements.txt (line 3)) (2.9.0.post0)\nCollecting MarkupSafe>=2.0 (from Jinja2>=3.0->sphinx<7,>=4.2->-r readthedocs-requirements.txt (line 4))\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/22/35/137da042dfb4720b638d2937c38a9c2df83fe32d20e8c8f3185dbfef05f7/MarkupSafe-3.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (20 kB)\nRequirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib->-r readthedocs-requirements.txt (line 3)) (1.17.0)\nRequirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.25.0->sphinx<7,>=4.2->-r readthedocs-requirements.txt (line 4)) (3.4.2)\nRequirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.25.0->sphinx<7,>=4.2->-r readthedocs-requirements.txt (line 4)) (3.10)\nRequirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.25.0->sphinx<7,>=4.2->-r readthedocs-requirements.txt (line 4)) (2.5.0)\nRequirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.25.0->sphinx<7,>=4.2->-r readthedocs-requirements.txt (line 4)) (2025.8.3)\nInstalling collected packages: sphinxcontrib-serializinghtml, sphinxcontrib-qthelp, sphinxcontrib-jsmath, sphinxcontrib-htmlhelp, sphinxcontrib-devhelp, sphinxcontrib-applehelp, snowballstemmer, MarkupSafe, imagesize, docutils, babel, alabaster, Jinja2, sphinx, numpydoc\n\nSuccessfully installed Jinja2-3.1.6 MarkupSafe-3.0.2 alabaster-0.7.16 babel-2.17.0 docutils-0.19 imagesize-1.4.1 numpydoc-1.9.0 snowballstemmer-3.0.1 sphinx-6.2.1 sphinxcontrib-applehelp-2.0.0 sphinxcontrib-devhelp-2.0.0 sphinxcontrib-htmlhelp-2.1.0 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-2.0.0 sphinxcontrib-serializinghtml-2.0.0\n",
    "stderr": "WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.\n",
    "execution_time": 11.207936763763428
  },
  {
    "command": "pytest",
    "success": false,
    "stdout": "============================= test session starts ==============================\nplatform linux -- Python 3.10.12, pytest-8.1.1, pluggy-1.6.0\nrootdir: /app/repo_to_process\nconfigfile: pyproject.toml\ncollected 98 items / 29 errors\n\n==================================== ERRORS ====================================\n_________________ ERROR collecting mahotas/tests/test_bbox.py __________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_bbox.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_bbox.py:4: in <module>\n    from mahotas import bbox\nmahotas/bbox.py:8: in <module>\n    from . import _bbox\nE   ImportError: cannot import name '_bbox' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n------------------------------- Captured stderr --------------------------------\nCould not import submodules (exact error was: cannot import name '_bbox' from partially initialized module 'mahotas' (most likely due to a circular import) (/app/repo_to_process/mahotas/__init__.py)).\n\nThere are many reasons for this error the most common one is that you have\neither not built the packages or have built (using `python setup.py build`) or\ninstalled them (using `python setup.py install`) and then proceeded to test\nmahotas **without changing the current directory**.\n\nTry installing and then changing to another directory before importing mahotas.\n________________ ERROR collecting mahotas/tests/test_bwperim.py ________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_bwperim.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_bwperim.py:1: in <module>\n    from mahotas import bwperim\nmahotas/bwperim.py:14: in <module>\n    from .labeled import bwperim\nmahotas/labeled.py:8: in <module>\n    from .morph import get_structuring_elem\nmahotas/morph.py:10: in <module>\n    from . import _morph\nE   ImportError: cannot import name '_morph' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n____________ ERROR collecting mahotas/tests/test_center_of_mass.py _____________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_center_of_mass.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_center_of_mass.py:3: in <module>\n    import mahotas.center_of_mass\nmahotas/center_of_mass.py:7: in <module>\n    from . import _center_of_mass\nE   ImportError: cannot import name '_center_of_mass' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n_______________ ERROR collecting mahotas/tests/test_convolve.py ________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_convolve.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_convolve.py:3: in <module>\n    import mahotas.convolve\nmahotas/convolve.py:8: in <module>\n    from . import _convolve\nE   ImportError: cannot import name '_convolve' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n_______________ ERROR collecting mahotas/tests/test_distance.py ________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_distance.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_distance.py:1: in <module>\n    from mahotas import distance\nmahotas/distance.py:6: in <module>\n    from . import _distance\nE   ImportError: cannot import name '_distance' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n_________________ ERROR collecting mahotas/tests/test_edge.py __________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_edge.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_edge.py:1: in <module>\n    from mahotas.edge import sobel\nmahotas/edge.py:9: in <module>\n    from . import convolve, gaussian_filter\nmahotas/convolve.py:8: in <module>\n    from . import _convolve\nE   ImportError: cannot import name '_convolve' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n_________________ ERROR collecting mahotas/tests/test_euler.py _________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_euler.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_euler.py:2: in <module>\n    from mahotas.euler import euler, _euler_lookup4, _euler_lookup8\nmahotas/euler.py:6: in <module>\n    from .convolve import convolve\nmahotas/convolve.py:8: in <module>\n    from . import _convolve\nE   ImportError: cannot import name '_convolve' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n____________ ERROR collecting mahotas/tests/test_features_shape.py _____________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_features_shape.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_features_shape.py:1: in <module>\n    import mahotas.features.shape\nmahotas/features/__init__.py:6: in <module>\n    from .texture import haralick\nmahotas/features/texture.py:8: in <module>\n    from . import _texture\nE   ImportError: cannot import name '_texture' from partially initialized module 'mahotas.features' (most likely due to a circular import) (/app/repo_to_process/mahotas/features/__init__.py)\n_______________ ERROR collecting mahotas/tests/test_gvoronoi.py ________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_gvoronoi.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_gvoronoi.py:2: in <module>\n    from mahotas.segmentation import gvoronoi\nmahotas/segmentation.py:12: in <module>\n    from . import _distance\nE   ImportError: cannot import name '_distance' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n_______________ ERROR collecting mahotas/tests/test_histogram.py _______________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_histogram.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_histogram.py:2: in <module>\n    from mahotas.histogram import fullhistogram\nmahotas/histogram.py:34: in <module>\n    from . import _histogram\nE   ImportError: cannot import name '_histogram' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n_______________ ERROR collecting mahotas/tests/test_imresize.py ________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_imresize.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_imresize.py:2: in <module>\n    from mahotas import imresize\nE   ImportError: cannot import name 'imresize' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n______________ ERROR collecting mahotas/tests/test_interpolate.py ______________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_interpolate.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_interpolate.py:1: in <module>\n    from mahotas import interpolate\nmahotas/interpolate.py:41: in <module>\n    from . import _interpolate\nE   ImportError: cannot import name '_interpolate' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n_________________ ERROR collecting mahotas/tests/test_label.py _________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_label.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_label.py:1: in <module>\n    from mahotas import label\nE   ImportError: cannot import name 'label' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n________________ ERROR collecting mahotas/tests/test_labeled.py ________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_labeled.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_labeled.py:3: in <module>\n    import mahotas.labeled\nmahotas/labeled.py:8: in <module>\n    from .morph import get_structuring_elem\nmahotas/morph.py:10: in <module>\n    from . import _morph\nE   ImportError: cannot import name '_morph' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n__________________ ERROR collecting mahotas/tests/test_lbp.py __________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_lbp.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_lbp.py:2: in <module>\n    from mahotas.features import _lbp\nmahotas/features/__init__.py:6: in <module>\n    from .texture import haralick\nmahotas/features/texture.py:8: in <module>\n    from . import _texture\nE   ImportError: cannot import name '_texture' from partially initialized module 'mahotas.features' (most likely due to a circular import) (/app/repo_to_process/mahotas/features/__init__.py)\n_______________ ERROR collecting mahotas/tests/test_majority.py ________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_majority.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_majority.py:2: in <module>\n    import mahotas.morph\nmahotas/morph.py:10: in <module>\n    from . import _morph\nE   ImportError: cannot import name '_morph' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n______________ ERROR collecting mahotas/tests/test_mean_filter.py ______________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_mean_filter.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_mean_filter.py:3: in <module>\n    from mahotas.convolve import mean_filter\nmahotas/convolve.py:8: in <module>\n    from . import _convolve\nE   ImportError: cannot import name '_convolve' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n_____________ ERROR collecting mahotas/tests/test_median_filter.py _____________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_median_filter.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_median_filter.py:2: in <module>\n    from mahotas.convolve import median_filter, rank_filter\nmahotas/convolve.py:8: in <module>\n    from . import _convolve\nE   ImportError: cannot import name '_convolve' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n________________ ERROR collecting mahotas/tests/test_moments.py ________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_moments.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_moments.py:3: in <module>\n    from mahotas.features.moments import moments\nmahotas/features/__init__.py:6: in <module>\n    from .texture import haralick\nmahotas/features/texture.py:8: in <module>\n    from . import _texture\nE   ImportError: cannot import name '_texture' from partially initialized module 'mahotas.features' (most likely due to a circular import) (/app/repo_to_process/mahotas/features/__init__.py)\n_________________ ERROR collecting mahotas/tests/test_morph.py _________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_morph.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_morph.py:3: in <module>\n    from mahotas.morph import get_structuring_elem, subm, tophat_open, tophat_close\nmahotas/morph.py:10: in <module>\n    from . import _morph\nE   ImportError: cannot import name '_morph' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n________________ ERROR collecting mahotas/tests/test_polygon.py ________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_polygon.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_polygon.py:3: in <module>\n    import mahotas.polygon\nmahotas/polygon.py:8: in <module>\n    from . import _convex\nE   ImportError: cannot import name '_convex' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n_____________ ERROR collecting mahotas/tests/test_segmentation.py ______________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_segmentation.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_segmentation.py:1: in <module>\n    import mahotas.segmentation\nmahotas/segmentation.py:12: in <module>\n    from . import _distance\nE   ImportError: cannot import name '_distance' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n_________________ ERROR collecting mahotas/tests/test_surf.py __________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_surf.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_surf.py:3: in <module>\n    import mahotas.features.surf as surf\nmahotas/features/__init__.py:6: in <module>\n    from .texture import haralick\nmahotas/features/texture.py:8: in <module>\n    from . import _texture\nE   ImportError: cannot import name '_texture' from partially initialized module 'mahotas.features' (most likely due to a circular import) (/app/repo_to_process/mahotas/features/__init__.py)\n____________ ERROR collecting mahotas/tests/test_surf_regression.py ____________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_surf_regression.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_surf_regression.py:3: in <module>\n    from mahotas.features.surf import surf\nmahotas/features/__init__.py:6: in <module>\n    from .texture import haralick\nmahotas/features/texture.py:8: in <module>\n    from . import _texture\nE   ImportError: cannot import name '_texture' from partially initialized module 'mahotas.features' (most likely due to a circular import) (/app/repo_to_process/mahotas/features/__init__.py)\n__________________ ERROR collecting mahotas/tests/test_tas.py __________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_tas.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_tas.py:2: in <module>\n    from mahotas.features import tas, pftas\nmahotas/features/__init__.py:6: in <module>\n    from .texture import haralick\nmahotas/features/texture.py:8: in <module>\n    from . import _texture\nE   ImportError: cannot import name '_texture' from partially initialized module 'mahotas.features' (most likely due to a circular import) (/app/repo_to_process/mahotas/features/__init__.py)\n____________ ERROR collecting mahotas/tests/test_template_match.py _____________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_template_match.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_template_match.py:2: in <module>\n    import mahotas.convolve\nmahotas/convolve.py:8: in <module>\n    from . import _convolve\nE   ImportError: cannot import name '_convolve' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n________________ ERROR collecting mahotas/tests/test_texture.py ________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_texture.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_texture.py:2: in <module>\n    from mahotas.features import texture\nmahotas/features/__init__.py:6: in <module>\n    from .texture import haralick\nmahotas/features/texture.py:8: in <module>\n    from . import _texture\nE   ImportError: cannot import name '_texture' from partially initialized module 'mahotas.features' (most likely due to a circular import) (/app/repo_to_process/mahotas/features/__init__.py)\n_____________ ERROR collecting mahotas/tests/test_thresholding.py ______________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_thresholding.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_thresholding.py:5: in <module>\n    from mahotas.thresholding import otsu, rc, bernsen, gbernsen\nmahotas/thresholding.py:46: in <module>\n    from .histogram import fullhistogram\nmahotas/histogram.py:34: in <module>\n    from . import _histogram\nE   ImportError: cannot import name '_histogram' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n________________ ERROR collecting mahotas/tests/test_zernike.py ________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_zernike.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_zernike.py:2: in <module>\n    from mahotas.features import zernike_moments\nmahotas/features/__init__.py:6: in <module>\n    from .texture import haralick\nmahotas/features/texture.py:8: in <module>\n    from . import _texture\nE   ImportError: cannot import name '_texture' from partially initialized module 'mahotas.features' (most likely due to a circular import) (/app/repo_to_process/mahotas/features/__init__.py)\n=============================== warnings summary ===============================\nmahotas/bwperim.py:7\n  /app/repo_to_process/mahotas/bwperim.py:7: DeprecationWarning: Use\n  \n  from mahotas.labeled import bwperim\n  \n    warnings.warn(\n\n-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html\n=========================== short test summary info ============================\nERROR mahotas/tests/test_bbox.py\nERROR mahotas/tests/test_bwperim.py\nERROR mahotas/tests/test_center_of_mass.py\nERROR mahotas/tests/test_convolve.py\nERROR mahotas/tests/test_distance.py\nERROR mahotas/tests/test_edge.py\nERROR mahotas/tests/test_euler.py\nERROR mahotas/tests/test_features_shape.py\nERROR mahotas/tests/test_gvoronoi.py\nERROR mahotas/tests/test_histogram.py\nERROR mahotas/tests/test_imresize.py\nERROR mahotas/tests/test_interpolate.py\nERROR mahotas/tests/test_label.py\nERROR mahotas/tests/test_labeled.py\nERROR mahotas/tests/test_lbp.py\nERROR mahotas/tests/test_majority.py\nERROR mahotas/tests/test_mean_filter.py\nERROR mahotas/tests/test_median_filter.py\nERROR mahotas/tests/test_moments.py\nERROR mahotas/tests/test_morph.py\nERROR mahotas/tests/test_polygon.py\nERROR mahotas/tests/test_segmentation.py\nERROR mahotas/tests/test_surf.py\nERROR mahotas/tests/test_surf_regression.py\nERROR mahotas/tests/test_tas.py\nERROR mahotas/tests/test_template_match.py\nERROR mahotas/tests/test_texture.py\nERROR mahotas/tests/test_thresholding.py\nERROR mahotas/tests/test_zernike.py\n!!!!!!!!!!!!!!!!!!! Interrupted: 29 errors during collection !!!!!!!!!!!!!!!!!!!\n======================== 1 warning, 29 errors in 1.13s =========================\n",
    "stderr": "",
    "execution_time": 1.3203232288360596
  }
]