[
  {
    "command": "if [ -f requirements.txt ]; then pip install -r requirements.txt; fi",
    "success": true,
    "stdout": "",
    "stderr": "",
    "execution_time": 0.000911712646484375
  },
  {
    "command": "if [ -f pyproject.toml ]; then pip install .; fi",
    "success": false,
    "stdout": "Looking in indexes: https://repo.huaweicloud.com/repository/pypi/simple/\nProcessing /app/repo_to_process\n  Installing build dependencies: started\n  Installing build dependencies: finished with status 'done'\n  Getting requirements to build wheel: started\n  Getting requirements to build wheel: finished with status 'done'\n  Preparing metadata (pyproject.toml): started\n  Preparing metadata (pyproject.toml): finished with status 'done'\nCollecting matplotlib (from sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/ac/64/8d0c8937dee86c286625bddb1902efacc3e22f2b619f5b5a8df29fe5217b/matplotlib-3.10.5-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.7 MB)\nCollecting meshio (from sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/89/5f/39cbadc320cd78f4834b0a9f7a2fa3c980dca942bf193f315837eacb8870/meshio-5.3.5-py3-none-any.whl (166 kB)\nRequirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b) (2.2.6)\nCollecting pyparsing (from sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/05/e7/df2285f3d08fee213f2d041540fa4fc9ca6c2d44cf36d3a035bf2a8d2bcc/pyparsing-3.2.3-py3-none-any.whl (111 kB)\nCollecting pyvista (from sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/59/39/a42bf1a87c9414ca6900ac694b92ed657300461913f0abe18d4364a716f1/pyvista-0.46.0-py3-none-any.whl (2.4 MB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 11.0 MB/s  0:00:00\nCollecting scipy (from sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/8e/6d/41991e503e51fc1134502694c5fa7a1671501a17ffa12716a4a9151af3df/scipy-1.15.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (37.7 MB)\nCollecting sympy (from sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/a2/09/77d55d46fd61b4a135c444fc97158ef34a095e5681d0a6c10b75bf356191/sympy-1.14.0-py3-none-any.whl (6.3 MB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 11.3 MB/s  0:00:00\nCollecting tables (from sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/0a/7d/3165c7538b8e89b22fa17ad68e04106cca7023cf68e94011ae7b3b6d2a78/tables-3.10.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.6 MB)\nRequirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b) (25.0)\nCollecting contourpy>=1.0.1 (from matplotlib->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/32/5c/1ee32d1c7956923202f00cf8d2a14a62ed7517bdc0ee1e55301227fc273c/contourpy-1.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (325 kB)\nCollecting cycler>=0.10 (from matplotlib->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/e7/05/c19819d5e3d95294a6f5947fb9b9629efb316b96de511b418c53d245aae6/cycler-0.12.1-py3-none-any.whl (8.3 kB)\nCollecting fonttools>=4.22.0 (from matplotlib->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/05/57/767e31e48861045d89691128bd81fd4c62b62150f9a17a666f731ce4f197/fonttools-4.59.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.8 MB)\nCollecting kiwisolver>=1.3.1 (from matplotlib->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/de/c6/7b9bb8044e150d4d1558423a1568e4f227193662a02231064e3824f37e0a/kiwisolver-1.4.8-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)\nCollecting pillow>=8 (from matplotlib->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/f0/16/1a6bf01fb622fb9cf5c91683823f073f053005c849b1f52ed613afcf8dae/pillow-11.3.0-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.6 MB)\nRequirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b) (2.9.0.post0)\nRequirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b) (1.17.0)\nCollecting rich (from meshio->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/e3/30/3c4d035596d3cf444529e0b2953ad0466f6049528a879d27534700580395/rich-14.1.0-py3-none-any.whl (243 kB)\nCollecting pooch (from pyvista->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/a8/87/77cc11c7a9ea9fd05503def69e3d18605852cd0d4b0d3b8f15bbeb3ef1d1/pooch-1.8.2-py3-none-any.whl (64 kB)\nCollecting scooby>=0.5.1 (from pyvista->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/56/fd/bff0921f2d6cad3a5083017abe1bcd318dc15e7a21cfa22dbdbf6dda2e11/scooby-0.10.1-py3-none-any.whl (18 kB)\nRequirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from pyvista->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b) (4.14.1)\nCollecting vtk!=9.4.0 (from pyvista->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/81/31/5a95a57d37c1b5087cdb5729e90dfb419250a545ab127477f1ffe5d65337/vtk-9.5.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (112.1 MB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.1/112.1 MB 5.9 MB/s  0:00:18\nCollecting platformdirs>=2.5.0 (from pooch->pyvista->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/fe/39/979e8e21520d4e47a0bbe349e2713c0aac6f3d853d0e5b34d76206c439aa/platformdirs-4.3.8-py3-none-any.whl (18 kB)\nRequirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from pooch->pyvista->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b) (2.32.4)\nRequirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->pooch->pyvista->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b) (3.4.2)\nRequirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->pooch->pyvista->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b) (3.10)\nRequirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->pooch->pyvista->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b) (2.5.0)\nRequirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->pooch->pyvista->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b) (2025.8.3)\nCollecting markdown-it-py>=2.2.0 (from rich->meshio->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/42/d7/1ec15b46af6af88f19b8e5ffea08fa375d433c998b8a7639e76935c14f1f/markdown_it_py-3.0.0-py3-none-any.whl (87 kB)\nRequirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich->meshio->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b) (2.19.2)\nCollecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->meshio->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/b3/38/89ba8ad64ae25be8de66a6d463314cf1eb366222074cfda9ee839c56a4b4/mdurl-0.1.2-py3-none-any.whl (10.0 kB)\nCollecting mpmath<1.4,>=1.1.0 (from sympy->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/43/e3/7d92a15f894aa0c9c4b49b8ee9ac9850d6e63b03c9c32c0367a13ae62209/mpmath-1.3.0-py3-none-any.whl (536 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 6.7 MB/s  0:00:00\nCollecting numexpr>=2.6.2 (from tables->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/83/03/0718f1ac2d7cc0422096ab0ac16cc04597539a2c69a22616d781a2be4359/numexpr-2.11.0-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (399 kB)\nCollecting py-cpuinfo (from tables->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/e0/a9/023730ba63db1e494a271cb018dcd361bd2c917ba7004c3e49d5daf795a2/py_cpuinfo-9.0.0-py3-none-any.whl (22 kB)\nCollecting blosc2>=2.3.0 (from tables->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/00/b5/b79ff462085b6b1fb4ce4075e2c3dc5cf4ad0e8e84a8452c62bf6f9a5194/blosc2-3.6.1-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.4 MB)\nCollecting ndindex (from blosc2>=2.3.0->tables->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/e3/a6/975bfec7bec7f274853b0c33953b5f2df4ad51f62d1aab0c7142fee98261/ndindex-1.10.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (501 kB)\nCollecting msgpack (from blosc2>=2.3.0->tables->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/20/8e/0bb8c977efecfe6ea7116e2ed73a78a8d32a947f94d272586cf02a9757db/msgpack-1.1.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (408 kB)\nBuilding wheels for collected packages: sfepy\n  Building wheel for sfepy (pyproject.toml): started\n  Building wheel for sfepy (pyproject.toml): finished with status 'error'\nFailed to build sfepy\n",
    "stderr": "  error: subprocess-exited-with-error\n  \n  × Building wheel for sfepy (pyproject.toml) did not run successfully.\n  │ exit code: 1\n  ╰─> [261 lines of output]\n      sympy (optional) is missing; some tests are going to fail!\n      igakit (optional) is missing; you may get run-time errors\n      petsc4py (optional) is missing; you may get run-time errors\n      mpi4py (optional) is missing; you may get run-time errors\n      slepc4py (optional) is missing; you may get run-time errors\n      pymetis (optional) is missing; you may get run-time errors\n      scikits.umfpack (optional) is missing; you may get run-time errors\n      psutil (optional) is missing; you may get run-time errors\n      pyvista (optional) is missing; you may get run-time errors\n      opt_einsum (optional) is missing; you may get run-time errors\n      jax (optional) is missing; you may get run-time errors\n      dask (optional) is missing; you may get run-time errors\n      primme (optional) is missing; you may get run-time errors\n      oct2py (optional) is missing; you may get run-time errors\n      mumpspy (optional) is missing; you may get run-time errors\n      mumps (optional) is missing; you may get run-time errors\n      ipctk (optional) is missing; you may get run-time errors\n      pypardiso (optional) is missing; you may get run-time errors\n      /tmp/pip-build-env-x_mqgj_d/overlay/local/lib/python3.10/dist-packages/setuptools/dist.py:759: SetuptoolsDeprecationWarning: License classifiers are deprecated.\n      !!\n      \n              ********************************************************************************\n              Please consider removing the following classifiers in favor of a SPDX license expression:\n      \n              License :: OSI Approved :: BSD License\n      \n              See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.\n              ********************************************************************************\n      \n      !!\n        self._finalize_license_expression()\n      \n      \n      --------------------------------------------------------------------------------\n      -- Trying 'Ninja' generator\n      --------------------------------\n      ---------------------------\n      ----------------------\n      -----------------\n      ------------\n      -------\n      --\n      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):\n        Compatibility with CMake < 3.10 will be removed from a future version of\n        CMake.\n      \n        Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax\n        to tell CMake that the project requires at least <min> but has been updated\n        to work with policies introduced by <max> or earlier.\n      \n      Not searching for unused variables given on the command line.\n      \n      -- The C compiler identification is GNU 11.4.0\n      -- Detecting C compiler ABI info\n      -- Detecting C compiler ABI info - done\n      -- Check for working C compiler: /usr/bin/cc - skipped\n      -- Detecting C compile features\n      -- Detecting C compile features - done\n      -- Configuring done (0.1s)\n      -- Generating done (0.0s)\n      -- Build files have been written to: /app/repo_to_process/_cmake_test_compile/build\n      --\n      -------\n      ------------\n      -----------------\n      ----------------------\n      ---------------------------\n      --------------------------------\n      -- Trying 'Ninja' generator - success\n      --------------------------------------------------------------------------------\n      \n      Configuring Project\n        Working directory:\n          /app/repo_to_process/_skbuild/linux-x86_64-3.10/cmake-build\n        Command:\n          /tmp/pip-build-env-x_mqgj_d/overlay/local/lib/python3.10/dist-packages/cmake/data/bin/cmake /app/repo_to_process -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-x_mqgj_d/overlay/local/lib/python3.10/dist-packages/ninja/data/bin/ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/app/repo_to_process/_skbuild/linux-x86_64-3.10/cmake-install -DPYTHON_VERSION_STRING:STRING=3.10.12 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-x_mqgj_d/overlay/local/lib/python3.10/dist-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/usr/bin/python3 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPython_EXECUTABLE:PATH=/usr/bin/python3 -DPython_ROOT_DIR:PATH=/usr -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPython_NumPy_INCLUDE_DIRS:PATH=/tmp/pip-build-env-x_mqgj_d/overlay/local/lib/python3.10/dist-packages/numpy/_core/include -DPython3_EXECUTABLE:PATH=/usr/bin/python3 -DPython3_ROOT_DIR:PATH=/usr -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPython3_NumPy_INCLUDE_DIRS:PATH=/tmp/pip-build-env-x_mqgj_d/overlay/local/lib/python3.10/dist-packages/numpy/_core/include -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-x_mqgj_d/overlay/local/lib/python3.10/dist-packages/ninja/data/bin/ninja '-DCMAKE_C_FLAGS=-g -O2 -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security' -DDEBUG_FMF=OFF -DDEBUG_MESH=OFF -DCMAKE_BUILD_TYPE:STRING=Release\n      \n      Not searching for unused variables given on the command line.\n      -- The C compiler identification is GNU 11.4.0\n      -- Detecting C compiler ABI info\n      -- Detecting C compiler ABI info - done\n      -- Check for working C compiler: /usr/bin/cc - skipped\n      -- Detecting C compile features\n      -- Detecting C compile features - done\n      CMake Warning (dev) at /tmp/pip-build-env-x_mqgj_d/overlay/local/lib/python3.10/dist-packages/skbuild/resources/cmake/FindPythonExtensions.cmake:245 (find_package):\n        Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules\n        are removed.  Run \"cmake --help-policy CMP0148\" for policy details.  Use\n        the cmake_policy command to set the policy and suppress this warning.\n      \n      Call Stack (most recent call first):\n        CMakeLists.txt:6 (find_package)\n      This warning is for project developers.  Use -Wno-dev to suppress it.\n      \n      -- Found PythonInterp: /usr/bin/python3 (found version \"3.10.12\")\n      CMake Warning (dev) at /tmp/pip-build-env-x_mqgj_d/overlay/local/lib/python3.10/dist-packages/skbuild/resources/cmake/FindPythonExtensions.cmake:248 (find_package):\n        Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules\n        are removed.  Run \"cmake --help-policy CMP0148\" for policy details.  Use\n        the cmake_policy command to set the policy and suppress this warning.\n      \n      Call Stack (most recent call first):\n        CMakeLists.txt:6 (find_package)\n      This warning is for project developers.  Use -Wno-dev to suppress it.\n      \n      -- Found PythonLibs: no-library-required\n      -- Found Cython: /tmp/pip-build-env-x_mqgj_d/overlay/local/bin/cython\n      -- Found NumPy: /tmp/pip-build-env-x_mqgj_d/overlay/local/lib/python3.10/dist-packages/numpy/_core/include (found version \"2.2.6\")\n      _modinit_prefix:PyInit_\n      _modinit_prefix:PyInit_\n      _modinit_prefix:PyInit_\n      _modinit_prefix:PyInit_\n      _modinit_prefix:PyInit_\n      _modinit_prefix:PyInit_\n      _modinit_prefix:PyInit_\n      _modinit_prefix:PyInit_\n      _modinit_prefix:PyInit_\n      _modinit_prefix:PyInit_\n      _modinit_prefix:PyInit_\n      -- Configuring done (1.1s)\n      -- Generating done (0.0s)\n      -- Build files have been written to: /app/repo_to_process/_skbuild/linux-x86_64-3.10/cmake-build\n      [1/66] Building C object sfepy/discrete/common/extmods/CMakeFiles/sfepy_common.dir/common_python.c.o\n      FAILED: sfepy/discrete/common/extmods/CMakeFiles/sfepy_common.dir/common_python.c.o\n      /usr/bin/cc -DNPY_NO_DEPRECATED_API=NPY_2_0_API_VERSION -DSFEPY_PLATFORM=0 -Dinline=inline -I/app/repo_to_process/_skbuild/linux-x86_64-3.10/cmake-build/sfepy/discrete/common/extmods -I/app/repo_to_process/sfepy/discrete/common/extmods -I/usr/include/python3.10 -I/tmp/pip-build-env-x_mqgj_d/overlay/local/lib/python3.10/dist-packages/numpy/_core/include -g -O2 -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -O3 -DNDEBUG -fPIC -MD -MT sfepy/discrete/common/extmods/CMakeFiles/sfepy_common.dir/common_python.c.o -MF sfepy/discrete/common/extmods/CMakeFiles/sfepy_common.dir/common_python.c.o.d -o sfepy/discrete/common/extmods/CMakeFiles/sfepy_common.dir/common_python.c.o -c /app/repo_to_process/sfepy/discrete/common/extmods/common_python.c\n      In file included from /app/repo_to_process/sfepy/discrete/common/extmods/common.h:12,\n                       from /app/repo_to_process/sfepy/discrete/common/extmods/common_python.c:3:\n      /app/repo_to_process/sfepy/discrete/common/extmods/types.h:4:10: fatal error: Python.h: No such file or directory\n          4 | #include <Python.h>\n            |          ^~~~~~~~~~\n      compilation terminated.\n      [2/66] Building C object sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/form_sdcc.c.o\n      FAILED: sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/form_sdcc.c.o\n      /usr/bin/cc -DNPY_NO_DEPRECATED_API=NPY_2_0_API_VERSION -DSFEPY_PLATFORM=0 -Dinline=inline -I/app/repo_to_process/_skbuild/linux-x86_64-3.10/cmake-build/sfepy/terms/extmods -I/app/repo_to_process/sfepy/terms/extmods -I/usr/include/python3.10 -I/tmp/pip-build-env-x_mqgj_d/overlay/local/lib/python3.10/dist-packages/numpy/_core/include -I/app/repo_to_process/sfepy/terms/extmods/../../discrete/common/extmods -g -O2 -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -O3 -DNDEBUG -fPIC -MD -MT sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/form_sdcc.c.o -MF sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/form_sdcc.c.o.d -o sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/form_sdcc.c.o -c /app/repo_to_process/sfepy/terms/extmods/form_sdcc.c\n      In file included from /app/repo_to_process/sfepy/terms/extmods/../../discrete/common/extmods/common.h:12,\n                       from /app/repo_to_process/sfepy/terms/extmods/form_sdcc.h:8,\n                       from /app/repo_to_process/sfepy/terms/extmods/form_sdcc.c:1:\n      /app/repo_to_process/sfepy/terms/extmods/../../discrete/common/extmods/types.h:4:10: fatal error: Python.h: No such file or directory\n          4 | #include <Python.h>\n            |          ^~~~~~~~~~\n      compilation terminated.\n      [3/66] Building C object sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_basic.c.o\n      FAILED: sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_basic.c.o\n      /usr/bin/cc -DNPY_NO_DEPRECATED_API=NPY_2_0_API_VERSION -DSFEPY_PLATFORM=0 -Dinline=inline -I/app/repo_to_process/_skbuild/linux-x86_64-3.10/cmake-build/sfepy/terms/extmods -I/app/repo_to_process/sfepy/terms/extmods -I/usr/include/python3.10 -I/tmp/pip-build-env-x_mqgj_d/overlay/local/lib/python3.10/dist-packages/numpy/_core/include -I/app/repo_to_process/sfepy/terms/extmods/../../discrete/common/extmods -g -O2 -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -O3 -DNDEBUG -fPIC -MD -MT sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_basic.c.o -MF sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_basic.c.o.d -o sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_basic.c.o -c /app/repo_to_process/sfepy/terms/extmods/terms_basic.c\n      In file included from /app/repo_to_process/sfepy/terms/extmods/../../discrete/common/extmods/common.h:12,\n                       from /app/repo_to_process/sfepy/terms/extmods/terms_basic.h:8,\n                       from /app/repo_to_process/sfepy/terms/extmods/terms_basic.c:1:\n      /app/repo_to_process/sfepy/terms/extmods/../../discrete/common/extmods/types.h:4:10: fatal error: Python.h: No such file or directory\n          4 | #include <Python.h>\n            |          ^~~~~~~~~~\n      compilation terminated.\n      [4/66] Building C object sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_biot.c.o\n      FAILED: sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_biot.c.o\n      /usr/bin/cc -DNPY_NO_DEPRECATED_API=NPY_2_0_API_VERSION -DSFEPY_PLATFORM=0 -Dinline=inline -I/app/repo_to_process/_skbuild/linux-x86_64-3.10/cmake-build/sfepy/terms/extmods -I/app/repo_to_process/sfepy/terms/extmods -I/usr/include/python3.10 -I/tmp/pip-build-env-x_mqgj_d/overlay/local/lib/python3.10/dist-packages/numpy/_core/include -I/app/repo_to_process/sfepy/terms/extmods/../../discrete/common/extmods -g -O2 -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -O3 -DNDEBUG -fPIC -MD -MT sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_biot.c.o -MF sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_biot.c.o.d -o sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_biot.c.o -c /app/repo_to_process/sfepy/terms/extmods/terms_biot.c\n      In file included from /app/repo_to_process/sfepy/terms/extmods/../../discrete/common/extmods/common.h:12,\n                       from /app/repo_to_process/sfepy/terms/extmods/terms_biot.h:8,\n                       from /app/repo_to_process/sfepy/terms/extmods/terms_biot.c:1:\n      /app/repo_to_process/sfepy/terms/extmods/../../discrete/common/extmods/types.h:4:10: fatal error: Python.h: No such file or directory\n          4 | #include <Python.h>\n            |          ^~~~~~~~~~\n      compilation terminated.\n      [5/66] Building C object sfepy/discrete/common/extmods/CMakeFiles/sfepy_common.dir/fmfield.c.o\n      FAILED: sfepy/discrete/common/extmods/CMakeFiles/sfepy_common.dir/fmfield.c.o\n      /usr/bin/cc -DNPY_NO_DEPRECATED_API=NPY_2_0_API_VERSION -DSFEPY_PLATFORM=0 -Dinline=inline -I/app/repo_to_process/_skbuild/linux-x86_64-3.10/cmake-build/sfepy/discrete/common/extmods -I/app/repo_to_process/sfepy/discrete/common/extmods -I/usr/include/python3.10 -I/tmp/pip-build-env-x_mqgj_d/overlay/local/lib/python3.10/dist-packages/numpy/_core/include -g -O2 -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -O3 -DNDEBUG -fPIC -MD -MT sfepy/discrete/common/extmods/CMakeFiles/sfepy_common.dir/fmfield.c.o -MF sfepy/discrete/common/extmods/CMakeFiles/sfepy_common.dir/fmfield.c.o.d -o sfepy/discrete/common/extmods/CMakeFiles/sfepy_common.dir/fmfield.c.o -c /app/repo_to_process/sfepy/discrete/common/extmods/fmfield.c\n      In file included from /app/repo_to_process/sfepy/discrete/common/extmods/common.h:12,\n                       from /app/repo_to_process/sfepy/discrete/common/extmods/fmfield.h:9,\n                       from /app/repo_to_process/sfepy/discrete/common/extmods/fmfield.c:1:\n      /app/repo_to_process/sfepy/discrete/common/extmods/types.h:4:10: fatal error: Python.h: No such file or directory\n          4 | #include <Python.h>\n            |          ^~~~~~~~~~\n      compilation terminated.\n      [6/66] Building C object sfepy/discrete/common/extmods/CMakeFiles/sfepy_common.dir/geommech.c.o\n      FAILED: sfepy/discrete/common/extmods/CMakeFiles/sfepy_common.dir/geommech.c.o\n      /usr/bin/cc -DNPY_NO_DEPRECATED_API=NPY_2_0_API_VERSION -DSFEPY_PLATFORM=0 -Dinline=inline -I/app/repo_to_process/_skbuild/linux-x86_64-3.10/cmake-build/sfepy/discrete/common/extmods -I/app/repo_to_process/sfepy/discrete/common/extmods -I/usr/include/python3.10 -I/tmp/pip-build-env-x_mqgj_d/overlay/local/lib/python3.10/dist-packages/numpy/_core/include -g -O2 -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -O3 -DNDEBUG -fPIC -MD -MT sfepy/discrete/common/extmods/CMakeFiles/sfepy_common.dir/geommech.c.o -MF sfepy/discrete/common/extmods/CMakeFiles/sfepy_common.dir/geommech.c.o.d -o sfepy/discrete/common/extmods/CMakeFiles/sfepy_common.dir/geommech.c.o -c /app/repo_to_process/sfepy/discrete/common/extmods/geommech.c\n      In file included from /app/repo_to_process/sfepy/discrete/common/extmods/common.h:12,\n                       from /app/repo_to_process/sfepy/discrete/common/extmods/geommech.h:8,\n                       from /app/repo_to_process/sfepy/discrete/common/extmods/geommech.c:1:\n      /app/repo_to_process/sfepy/discrete/common/extmods/types.h:4:10: fatal error: Python.h: No such file or directory\n          4 | #include <Python.h>\n            |          ^~~~~~~~~~\n      compilation terminated.\n      [7/66] Building C object sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_adj_navier_stokes.c.o\n      FAILED: sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_adj_navier_stokes.c.o\n      /usr/bin/cc -DNPY_NO_DEPRECATED_API=NPY_2_0_API_VERSION -DSFEPY_PLATFORM=0 -Dinline=inline -I/app/repo_to_process/_skbuild/linux-x86_64-3.10/cmake-build/sfepy/terms/extmods -I/app/repo_to_process/sfepy/terms/extmods -I/usr/include/python3.10 -I/tmp/pip-build-env-x_mqgj_d/overlay/local/lib/python3.10/dist-packages/numpy/_core/include -I/app/repo_to_process/sfepy/terms/extmods/../../discrete/common/extmods -g -O2 -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -O3 -DNDEBUG -fPIC -MD -MT sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_adj_navier_stokes.c.o -MF sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_adj_navier_stokes.c.o.d -o sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_adj_navier_stokes.c.o -c /app/repo_to_process/sfepy/terms/extmods/terms_adj_navier_stokes.c\n      In file included from /app/repo_to_process/sfepy/terms/extmods/../../discrete/common/extmods/common.h:12,\n                       from /app/repo_to_process/sfepy/terms/extmods/terms_navier_stokes.h:8,\n                       from /app/repo_to_process/sfepy/terms/extmods/terms_adj_navier_stokes.c:1:\n      /app/repo_to_process/sfepy/terms/extmods/../../discrete/common/extmods/types.h:4:10: fatal error: Python.h: No such file or directory\n          4 | #include <Python.h>\n            |          ^~~~~~~~~~\n      compilation terminated.\n      [8/66] Building C object sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_hyperelastic.c.o\n      FAILED: sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_hyperelastic.c.o\n      /usr/bin/cc -DNPY_NO_DEPRECATED_API=NPY_2_0_API_VERSION -DSFEPY_PLATFORM=0 -Dinline=inline -I/app/repo_to_process/_skbuild/linux-x86_64-3.10/cmake-build/sfepy/terms/extmods -I/app/repo_to_process/sfepy/terms/extmods -I/usr/include/python3.10 -I/tmp/pip-build-env-x_mqgj_d/overlay/local/lib/python3.10/dist-packages/numpy/_core/include -I/app/repo_to_process/sfepy/terms/extmods/../../discrete/common/extmods -g -O2 -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -O3 -DNDEBUG -fPIC -MD -MT sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_hyperelastic.c.o -MF sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_hyperelastic.c.o.d -o sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_hyperelastic.c.o -c /app/repo_to_process/sfepy/terms/extmods/terms_hyperelastic.c\n      In file included from /app/repo_to_process/sfepy/terms/extmods/../../discrete/common/extmods/common.h:12,\n                       from /app/repo_to_process/sfepy/terms/extmods/terms_hyperelastic.h:4,\n                       from /app/repo_to_process/sfepy/terms/extmods/terms_hyperelastic.c:1:\n      /app/repo_to_process/sfepy/terms/extmods/../../discrete/common/extmods/types.h:4:10: fatal error: Python.h: No such file or directory\n          4 | #include <Python.h>\n            |          ^~~~~~~~~~\n      compilation terminated.\n      [9/66] Building C object sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_diffusion.c.o\n      FAILED: sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_diffusion.c.o\n      /usr/bin/cc -DNPY_NO_DEPRECATED_API=NPY_2_0_API_VERSION -DSFEPY_PLATFORM=0 -Dinline=inline -I/app/repo_to_process/_skbuild/linux-x86_64-3.10/cmake-build/sfepy/terms/extmods -I/app/repo_to_process/sfepy/terms/extmods -I/usr/include/python3.10 -I/tmp/pip-build-env-x_mqgj_d/overlay/local/lib/python3.10/dist-packages/numpy/_core/include -I/app/repo_to_process/sfepy/terms/extmods/../../discrete/common/extmods -g -O2 -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -O3 -DNDEBUG -fPIC -MD -MT sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_diffusion.c.o -MF sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_diffusion.c.o.d -o sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_diffusion.c.o -c /app/repo_to_process/sfepy/terms/extmods/terms_diffusion.c\n      In file included from /app/repo_to_process/sfepy/terms/extmods/../../discrete/common/extmods/common.h:12,\n                       from /app/repo_to_process/sfepy/terms/extmods/terms_diffusion.h:8,\n                       from /app/repo_to_process/sfepy/terms/extmods/terms_diffusion.c:1:\n      /app/repo_to_process/sfepy/terms/extmods/../../discrete/common/extmods/types.h:4:10: fatal error: Python.h: No such file or directory\n          4 | #include <Python.h>\n            |          ^~~~~~~~~~\n      compilation terminated.\n      [10/66] Building C object sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_dot.c.o\n      FAILED: sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_dot.c.o\n      /usr/bin/cc -DNPY_NO_DEPRECATED_API=NPY_2_0_API_VERSION -DSFEPY_PLATFORM=0 -Dinline=inline -I/app/repo_to_process/_skbuild/linux-x86_64-3.10/cmake-build/sfepy/terms/extmods -I/app/repo_to_process/sfepy/terms/extmods -I/usr/include/python3.10 -I/tmp/pip-build-env-x_mqgj_d/overlay/local/lib/python3.10/dist-packages/numpy/_core/include -I/app/repo_to_process/sfepy/terms/extmods/../../discrete/common/extmods -g -O2 -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -O3 -DNDEBUG -fPIC -MD -MT sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_dot.c.o -MF sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_dot.c.o.d -o sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_dot.c.o -c /app/repo_to_process/sfepy/terms/extmods/terms_dot.c\n      In file included from /app/repo_to_process/sfepy/terms/extmods/../../discrete/common/extmods/common.h:12,\n                       from /app/repo_to_process/sfepy/terms/extmods/terms.h:8,\n                       from /app/repo_to_process/sfepy/terms/extmods/terms_dot.c:1:\n      /app/repo_to_process/sfepy/terms/extmods/../../discrete/common/extmods/types.h:4:10: fatal error: Python.h: No such file or directory\n          4 | #include <Python.h>\n            |          ^~~~~~~~~~\n      compilation terminated.\n      [11/66] Building C object sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_elastic.c.o\n      FAILED: sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_elastic.c.o\n      /usr/bin/cc -DNPY_NO_DEPRECATED_API=NPY_2_0_API_VERSION -DSFEPY_PLATFORM=0 -Dinline=inline -I/app/repo_to_process/_skbuild/linux-x86_64-3.10/cmake-build/sfepy/terms/extmods -I/app/repo_to_process/sfepy/terms/extmods -I/usr/include/python3.10 -I/tmp/pip-build-env-x_mqgj_d/overlay/local/lib/python3.10/dist-packages/numpy/_core/include -I/app/repo_to_process/sfepy/terms/extmods/../../discrete/common/extmods -g -O2 -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -O3 -DNDEBUG -fPIC -MD -MT sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_elastic.c.o -MF sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_elastic.c.o.d -o sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_elastic.c.o -c /app/repo_to_process/sfepy/terms/extmods/terms_elastic.c\n      In file included from /app/repo_to_process/sfepy/terms/extmods/../../discrete/common/extmods/common.h:12,\n                       from /app/repo_to_process/sfepy/terms/extmods/form_sdcc.h:8,\n                       from /app/repo_to_process/sfepy/terms/extmods/terms_elastic.c:1:\n      /app/repo_to_process/sfepy/terms/extmods/../../discrete/common/extmods/types.h:4:10: fatal error: Python.h: No such file or directory\n          4 | #include <Python.h>\n            |          ^~~~~~~~~~\n      compilation terminated.\n      [12/66] Building C object sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_electric.c.o\n      FAILED: sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_electric.c.o\n      /usr/bin/cc -DNPY_NO_DEPRECATED_API=NPY_2_0_API_VERSION -DSFEPY_PLATFORM=0 -Dinline=inline -I/app/repo_to_process/_skbuild/linux-x86_64-3.10/cmake-build/sfepy/terms/extmods -I/app/repo_to_process/sfepy/terms/extmods -I/usr/include/python3.10 -I/tmp/pip-build-env-x_mqgj_d/overlay/local/lib/python3.10/dist-packages/numpy/_core/include -I/app/repo_to_process/sfepy/terms/extmods/../../discrete/common/extmods -g -O2 -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -O3 -DNDEBUG -fPIC -MD -MT sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_electric.c.o -MF sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_electric.c.o.d -o sfepy/terms/extmods/CMakeFiles/sfepy_terms.dir/terms_electric.c.o -c /app/repo_to_process/sfepy/terms/extmods/terms_electric.c\n      In file included from /app/repo_to_process/sfepy/terms/extmods/../../discrete/common/extmods/common.h:12,\n                       from /app/repo_to_process/sfepy/terms/extmods/terms_electric.h:8,\n                       from /app/repo_to_process/sfepy/terms/extmods/terms_electric.c:1:\n      /app/repo_to_process/sfepy/terms/extmods/../../discrete/common/extmods/types.h:4:10: fatal error: Python.h: No such file or directory\n          4 | #include <Python.h>\n            |          ^~~~~~~~~~\n      compilation terminated.\n      [13/66] Generating C source sfepy/discrete/common/extmods/assemble.c\n      [14/66] Generating C source sfepy/discrete/common/extmods/cmesh.c\n      ninja: build stopped: subcommand failed.\n      Traceback (most recent call last):\n        File \"/tmp/pip-build-env-x_mqgj_d/overlay/local/lib/python3.10/dist-packages/skbuild/setuptools_wrap.py\", line 668, in setup\n          cmkr.make(make_args, install_target=cmake_install_target, env=env)\n        File \"/tmp/pip-build-env-x_mqgj_d/overlay/local/lib/python3.10/dist-packages/skbuild/cmaker.py\", line 696, in make\n          self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)\n        File \"/tmp/pip-build-env-x_mqgj_d/overlay/local/lib/python3.10/dist-packages/skbuild/cmaker.py\", line 741, in make_impl\n          raise SKBuildError(msg)\n      \n      An error occurred while building with CMake.\n        Command:\n          /tmp/pip-build-env-x_mqgj_d/overlay/local/lib/python3.10/dist-packages/cmake/data/bin/cmake --build . --target install --config Release --\n        Install target:\n          install\n        Source directory:\n          /app/repo_to_process\n        Working directory:\n          /app/repo_to_process/_skbuild/linux-x86_64-3.10/cmake-build\n      Please check the install target is valid and see CMake's output for more information.\n      \n      [end of output]\n  \n  note: This error originates from a subprocess, and is likely not a problem with pip.\n  ERROR: Failed building wheel for sfepy\nerror: failed-wheel-build-for-install\n\n× Failed to build installable wheels for some pyproject.toml based projects\n╰─> sfepy\n",
    "execution_time": 72.92267775535583
  },
  {
    "command": "if [ -f setup.py ]; then pip install .; fi",
    "success": false,
    "stdout": "Looking in indexes: https://repo.huaweicloud.com/repository/pypi/simple/\nProcessing /app/repo_to_process\n  Installing build dependencies: started\n  Installing build dependencies: finished with status 'done'\n  Getting requirements to build wheel: started\n  Getting requirements to build wheel: finished with status 'done'\n  Preparing metadata (pyproject.toml): started\n  Preparing metadata (pyproject.toml): finished with status 'done'\nCollecting matplotlib (from sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/ac/64/8d0c8937dee86c286625bddb1902efacc3e22f2b619f5b5a8df29fe5217b/matplotlib-3.10.5-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.7 MB)\nCollecting meshio (from sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/89/5f/39cbadc320cd78f4834b0a9f7a2fa3c980dca942bf193f315837eacb8870/meshio-5.3.5-py3-none-any.whl (166 kB)\nRequirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b) (2.2.6)\nCollecting pyparsing (from sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/05/e7/df2285f3d08fee213f2d041540fa4fc9ca6c2d44cf36d3a035bf2a8d2bcc/pyparsing-3.2.3-py3-none-any.whl (111 kB)\nCollecting pyvista (from sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/59/39/a42bf1a87c9414ca6900ac694b92ed657300461913f0abe18d4364a716f1/pyvista-0.46.0-py3-none-any.whl (2.4 MB)\nCollecting scipy (from sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/8e/6d/41991e503e51fc1134502694c5fa7a1671501a17ffa12716a4a9151af3df/scipy-1.15.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (37.7 MB)\nCollecting sympy (from sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/a2/09/77d55d46fd61b4a135c444fc97158ef34a095e5681d0a6c10b75bf356191/sympy-1.14.0-py3-none-any.whl (6.3 MB)\nCollecting tables (from sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/0a/7d/3165c7538b8e89b22fa17ad68e04106cca7023cf68e94011ae7b3b6d2a78/tables-3.10.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.6 MB)\nRequirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b) (25.0)\nCollecting contourpy>=1.0.1 (from matplotlib->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/32/5c/1ee32d1c7956923202f00cf8d2a14a62ed7517bdc0ee1e55301227fc273c/contourpy-1.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (325 kB)\nCollecting cycler>=0.10 (from matplotlib->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/e7/05/c19819d5e3d95294a6f5947fb9b9629efb316b96de511b418c53d245aae6/cycler-0.12.1-py3-none-any.whl (8.3 kB)\nCollecting fonttools>=4.22.0 (from matplotlib->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/05/57/767e31e48861045d89691128bd81fd4c62b62150f9a17a666f731ce4f197/fonttools-4.59.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.8 MB)\nCollecting kiwisolver>=1.3.1 (from matplotlib->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/de/c6/7b9bb8044e150d4d1558423a1568e4f227193662a02231064e3824f37e0a/kiwisolver-1.4.8-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)\nCollecting pillow>=8 (from matplotlib->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/f0/16/1a6bf01fb622fb9cf5c91683823f073f053005c849b1f52ed613afcf8dae/pillow-11.3.0-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.6 MB)\nRequirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b) (2.9.0.post0)\nRequirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b) (1.17.0)\nCollecting rich (from meshio->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/e3/30/3c4d035596d3cf444529e0b2953ad0466f6049528a879d27534700580395/rich-14.1.0-py3-none-any.whl (243 kB)\nCollecting pooch (from pyvista->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/a8/87/77cc11c7a9ea9fd05503def69e3d18605852cd0d4b0d3b8f15bbeb3ef1d1/pooch-1.8.2-py3-none-any.whl (64 kB)\nCollecting scooby>=0.5.1 (from pyvista->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/56/fd/bff0921f2d6cad3a5083017abe1bcd318dc15e7a21cfa22dbdbf6dda2e11/scooby-0.10.1-py3-none-any.whl (18 kB)\nRequirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from pyvista->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b) (4.14.1)\nCollecting vtk!=9.4.0 (from pyvista->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/81/31/5a95a57d37c1b5087cdb5729e90dfb419250a545ab127477f1ffe5d65337/vtk-9.5.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (112.1 MB)\nCollecting platformdirs>=2.5.0 (from pooch->pyvista->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/fe/39/979e8e21520d4e47a0bbe349e2713c0aac6f3d853d0e5b34d76206c439aa/platformdirs-4.3.8-py3-none-any.whl (18 kB)\nRequirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from pooch->pyvista->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b) (2.32.4)\nRequirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->pooch->pyvista->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b) (3.4.2)\nRequirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->pooch->pyvista->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b) (3.10)\nRequirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->pooch->pyvista->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b) (2.5.0)\nRequirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->pooch->pyvista->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b) (2025.8.3)\nCollecting markdown-it-py>=2.2.0 (from rich->meshio->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/42/d7/1ec15b46af6af88f19b8e5ffea08fa375d433c998b8a7639e76935c14f1f/markdown_it_py-3.0.0-py3-none-any.whl (87 kB)\nRequirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich->meshio->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b) (2.19.2)\nCollecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->meshio->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/b3/38/89ba8ad64ae25be8de66a6d463314cf1eb366222074cfda9ee839c56a4b4/mdurl-0.1.2-py3-none-any.whl (10.0 kB)\nCollecting mpmath<1.4,>=1.1.0 (from sympy->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/43/e3/7d92a15f894aa0c9c4b49b8ee9ac9850d6e63b03c9c32c0367a13ae62209/mpmath-1.3.0-py3-none-any.whl (536 kB)\nCollecting numexpr>=2.6.2 (from tables->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/83/03/0718f1ac2d7cc0422096ab0ac16cc04597539a2c69a22616d781a2be4359/numexpr-2.11.0-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (399 kB)\nCollecting py-cpuinfo (from tables->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/e0/a9/023730ba63db1e494a271cb018dcd361bd2c917ba7004c3e49d5daf795a2/py_cpuinfo-9.0.0-py3-none-any.whl (22 kB)\nCollecting blosc2>=2.3.0 (from tables->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/00/b5/b79ff462085b6b1fb4ce4075e2c3dc5cf4ad0e8e84a8452c62bf6f9a5194/blosc2-3.6.1-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.4 MB)\nCollecting ndindex (from blosc2>=2.3.0->tables->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/e3/a6/975bfec7bec7f274853b0c33953b5f2df4ad51f62d1aab0c7142fee98261/ndindex-1.10.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (501 kB)\nCollecting msgpack (from blosc2>=2.3.0->tables->sfepy==2025.2+git.542d54540c78a2422bbf4042bb7b28751e62905b)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/20/8e/0bb8c977efecfe6ea7116e2ed73a78a8d32a947f94d272586cf02a9757db/msgpack-1.1.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (408 kB)\nBuilding wheels for collected packages: sfepy\n  Building wheel for sfepy (pyproject.toml): started\n  Building wheel for sfepy (pyproject.toml): finished with status 'error'\nFailed to build sfepy\n",
    "stderr": "  error: subprocess-exited-with-error\n  \n  × Building wheel for sfepy (pyproject.toml) did not run successfully.\n  │ exit code: 1\n  ╰─> [131 lines of output]\n      sympy (optional) is missing; some tests are going to fail!\n      igakit (optional) is missing; you may get run-time errors\n      petsc4py (optional) is missing; you may get run-time errors\n      mpi4py (optional) is missing; you may get run-time errors\n      slepc4py (optional) is missing; you may get run-time errors\n      pymetis (optional) is missing; you may get run-time errors\n      scikits.umfpack (optional) is missing; you may get run-time errors\n      psutil (optional) is missing; you may get run-time errors\n      pyvista (optional) is missing; you may get run-time errors\n      opt_einsum (optional) is missing; you may get run-time errors\n      jax (optional) is missing; you may get run-time errors\n      dask (optional) is missing; you may get run-time errors\n      primme (optional) is missing; you may get run-time errors\n      oct2py (optional) is missing; you may get run-time errors\n      mumpspy (optional) is missing; you may get run-time errors\n      mumps (optional) is missing; you may get run-time errors\n      ipctk (optional) is missing; you may get run-time errors\n      pypardiso (optional) is missing; you may get run-time errors\n      /tmp/pip-build-env-6cozc_l1/overlay/local/lib/python3.10/dist-packages/setuptools/dist.py:759: SetuptoolsDeprecationWarning: License classifiers are deprecated.\n      !!\n      \n              ********************************************************************************\n              Please consider removing the following classifiers in favor of a SPDX license expression:\n      \n              License :: OSI Approved :: BSD License\n      \n              See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.\n              ********************************************************************************\n      \n      !!\n        self._finalize_license_expression()\n      \n      \n      --------------------------------------------------------------------------------\n      -- Trying 'Ninja' generator\n      --------------------------------\n      ---------------------------\n      ----------------------\n      -----------------\n      ------------\n      -------\n      --\n      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):\n        Compatibility with CMake < 3.10 will be removed from a future version of\n        CMake.\n      \n        Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax\n        to tell CMake that the project requires at least <min> but has been updated\n        to work with policies introduced by <max> or earlier.\n      \n      Not searching for unused variables given on the command line.\n      \n      -- The C compiler identification is GNU 11.4.0\n      -- Detecting C compiler ABI info\n      -- Detecting C compiler ABI info - done\n      -- Check for working C compiler: /usr/bin/cc - skipped\n      -- Detecting C compile features\n      -- Detecting C compile features - done\n      -- Configuring done (0.1s)\n      -- Generating done (0.0s)\n      -- Build files have been written to: /app/repo_to_process/_cmake_test_compile/build\n      --\n      -------\n      ------------\n      -----------------\n      ----------------------\n      ---------------------------\n      --------------------------------\n      -- Trying 'Ninja' generator - success\n      --------------------------------------------------------------------------------\n      \n      Configuring Project\n        Working directory:\n          /app/repo_to_process/_skbuild/linux-x86_64-3.10/cmake-build\n        Command:\n          /tmp/pip-build-env-6cozc_l1/overlay/local/lib/python3.10/dist-packages/cmake/data/bin/cmake /app/repo_to_process -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-6cozc_l1/overlay/local/lib/python3.10/dist-packages/ninja/data/bin/ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/app/repo_to_process/_skbuild/linux-x86_64-3.10/cmake-install -DPYTHON_VERSION_STRING:STRING=3.10.12 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-6cozc_l1/overlay/local/lib/python3.10/dist-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/usr/bin/python3 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPython_EXECUTABLE:PATH=/usr/bin/python3 -DPython_ROOT_DIR:PATH=/usr -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPython_NumPy_INCLUDE_DIRS:PATH=/tmp/pip-build-env-6cozc_l1/overlay/local/lib/python3.10/dist-packages/numpy/_core/include -DPython3_EXECUTABLE:PATH=/usr/bin/python3 -DPython3_ROOT_DIR:PATH=/usr -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPython3_NumPy_INCLUDE_DIRS:PATH=/tmp/pip-build-env-6cozc_l1/overlay/local/lib/python3.10/dist-packages/numpy/_core/include -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-6cozc_l1/overlay/local/lib/python3.10/dist-packages/ninja/data/bin/ninja '-DCMAKE_C_FLAGS=-g -O2 -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security' -DDEBUG_FMF=OFF -DDEBUG_MESH=OFF -DCMAKE_BUILD_TYPE:STRING=Release\n      \n      CMake Warning (dev) at /tmp/pip-build-env-6cozc_l1/overlay/local/lib/python3.10/dist-packages/skbuild/resources/cmake/FindPythonExtensions.cmake:245 (find_package):\n        Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules\n        are removed.  Run \"cmake --help-policy CMP0148\" for policy details.  Use\n        the cmake_policy command to set the policy and suppress this warning.\n      \n      Call Stack (most recent call first):\n        CMakeLists.txt:6 (find_package)\n      This warning is for project developers.  Use -Wno-dev to suppress it.\n      Not searching for unused variables given on the command line.\n      \n      CMake Warning (dev) at /tmp/pip-build-env-6cozc_l1/overlay/local/lib/python3.10/dist-packages/skbuild/resources/cmake/FindPythonExtensions.cmake:248 (find_package):\n        Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules\n        are removed.  Run \"cmake --help-policy CMP0148\" for policy details.  Use\n        the cmake_policy command to set the policy and suppress this warning.\n      \n      Call Stack (most recent call first):\n        CMakeLists.txt:6 (find_package)\n      This warning is for project developers.  Use -Wno-dev to suppress it.\n      \n      CMake Error at /tmp/pip-build-env-6cozc_l1/overlay/local/lib/python3.10/dist-packages/skbuild/resources/cmake/FindCython.cmake:71 (message):\n        Command \"/tmp/pip-build-env-x_mqgj_d/overlay/local/bin/cython;--version\"\n        failed with output:\n      \n      Call Stack (most recent call first):\n        CMakeLists.txt:7 (find_package)\n      \n      \n      _modinit_prefix:PyInit_\n      _modinit_prefix:PyInit_\n      _modinit_prefix:PyInit_\n      _modinit_prefix:PyInit_\n      _modinit_prefix:PyInit_\n      _modinit_prefix:PyInit_\n      _modinit_prefix:PyInit_\n      _modinit_prefix:PyInit_\n      _modinit_prefix:PyInit_\n      _modinit_prefix:PyInit_\n      _modinit_prefix:PyInit_\n      -- Configuring incomplete, errors occurred!\n      Traceback (most recent call last):\n        File \"/tmp/pip-build-env-6cozc_l1/overlay/local/lib/python3.10/dist-packages/skbuild/setuptools_wrap.py\", line 660, in setup\n          env = cmkr.configure(\n        File \"/tmp/pip-build-env-6cozc_l1/overlay/local/lib/python3.10/dist-packages/skbuild/cmaker.py\", line 354, in configure\n          raise SKBuildError(msg)\n      \n      An error occurred while configuring with CMake.\n        Command:\n          /tmp/pip-build-env-6cozc_l1/overlay/local/lib/python3.10/dist-packages/cmake/data/bin/cmake /app/repo_to_process -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-6cozc_l1/overlay/local/lib/python3.10/dist-packages/ninja/data/bin/ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/app/repo_to_process/_skbuild/linux-x86_64-3.10/cmake-install -DPYTHON_VERSION_STRING:STRING=3.10.12 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-6cozc_l1/overlay/local/lib/python3.10/dist-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/usr/bin/python3 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPython_EXECUTABLE:PATH=/usr/bin/python3 -DPython_ROOT_DIR:PATH=/usr -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPython_NumPy_INCLUDE_DIRS:PATH=/tmp/pip-build-env-6cozc_l1/overlay/local/lib/python3.10/dist-packages/numpy/_core/include -DPython3_EXECUTABLE:PATH=/usr/bin/python3 -DPython3_ROOT_DIR:PATH=/usr -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPython3_NumPy_INCLUDE_DIRS:PATH=/tmp/pip-build-env-6cozc_l1/overlay/local/lib/python3.10/dist-packages/numpy/_core/include -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-6cozc_l1/overlay/local/lib/python3.10/dist-packages/ninja/data/bin/ninja '-DCMAKE_C_FLAGS=-g -O2 -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security' -DDEBUG_FMF=OFF -DDEBUG_MESH=OFF -DCMAKE_BUILD_TYPE:STRING=Release\n        Source directory:\n          /app/repo_to_process\n        Working directory:\n          /app/repo_to_process/_skbuild/linux-x86_64-3.10/cmake-build\n      Please see CMake's output for more information.\n      \n      [end of output]\n  \n  note: This error originates from a subprocess, and is likely not a problem with pip.\n  ERROR: Failed building wheel for sfepy\nerror: failed-wheel-build-for-install\n\n× Failed to build installable wheels for some pyproject.toml based projects\n╰─> sfepy\n",
    "execution_time": 24.316644191741943
  },
  {
    "command": "pytest",
    "success": false,
    "stdout": "============================= test session starts ==============================\nplatform linux -- Python 3.10.12, pytest-8.4.1, pluggy-1.6.0\nrootdir: /app/repo_to_process\nconfigfile: pytest.ini\ncollected 1 item / 50 errors\n\n==================================== ERRORS ====================================\n________________ ERROR collecting sfepy/scripts/test_install.py ________________\nImportError while importing test module '/app/repo_to_process/sfepy/scripts/test_install.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/__init__.py:3: in <module>\n    from .config import in_source_tree, top_dir, site_config\nsfepy/config.py:165: in <module>\n    site_config = Config()\nsfepy/config.py:64: in __init__\n    from sfepy.base.base import sfepy_config_dir\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n_______________ ERROR collecting sfepy/tests/test_assembling.py ________________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_assembling.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_assembling.py:2: in <module>\n    import scipy.sparse as sps\nE   ModuleNotFoundError: No module named 'scipy'\n__________________ ERROR collecting sfepy/tests/test_base.py ___________________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_base.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_base.py:1: in <module>\n    from sfepy.base.base import assert_\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n__________________ ERROR collecting sfepy/tests/test_cmesh.py __________________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_cmesh.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_cmesh.py:6: in <module>\n    import sfepy.base.testing as tst\nsfepy/base/testing.py:7: in <module>\n    from sfepy.base.base import Struct, assert_, IndexedStruct\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n_______________ ERROR collecting sfepy/tests/test_conditions.py ________________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_conditions.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_conditions.py:6: in <module>\n    import sfepy.base.testing as tst\nsfepy/base/testing.py:7: in <module>\n    from sfepy.base.base import Struct, assert_, IndexedStruct\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n__________ ERROR collecting sfepy/tests/test_declarative_examples.py ___________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_declarative_examples.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_declarative_examples.py:3: in <module>\n    from sfepy.base.testing import check_conditions, run_declaratice_example\nsfepy/base/testing.py:7: in <module>\n    from sfepy.base.base import Struct, assert_, IndexedStruct\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n________________ ERROR collecting sfepy/tests/test_dg_field.py _________________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_dg_field.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_dg_field.py:4: in <module>\n    from sfepy.base.base import Struct\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n_____________ ERROR collecting sfepy/tests/test_dg_terms_calls.py ______________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_dg_terms_calls.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_dg_terms_calls.py:7: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n_________________ ERROR collecting sfepy/tests/test_domain.py __________________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_domain.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_domain.py:6: in <module>\n    from sfepy import data_dir\nsfepy/__init__.py:3: in <module>\n    from .config import in_source_tree, top_dir, site_config\nsfepy/config.py:165: in <module>\n    site_config = Config()\nsfepy/config.py:64: in __init__\n    from sfepy.base.base import sfepy_config_dir\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n_______________ ERROR collecting sfepy/tests/test_ed_solvers.py ________________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_ed_solvers.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_ed_solvers.py:6: in <module>\n    from sfepy.discrete.fem.meshio import UserMeshIO\nsfepy/__init__.py:3: in <module>\n    from .config import in_source_tree, top_dir, site_config\nsfepy/config.py:165: in <module>\n    site_config = Config()\nsfepy/config.py:64: in __init__\n    from sfepy.base.base import sfepy_config_dir\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n___________ ERROR collecting sfepy/tests/test_eigenvalue_solvers.py ____________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_eigenvalue_solvers.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_eigenvalue_solvers.py:4: in <module>\n    from sfepy.discrete.fem.meshio import UserMeshIO\nsfepy/__init__.py:3: in <module>\n    from .config import in_source_tree, top_dir, site_config\nsfepy/config.py:165: in <module>\n    site_config = Config()\nsfepy/config.py:64: in __init__\n    from sfepy.base.base import sfepy_config_dir\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n_________ ERROR collecting sfepy/tests/test_elasticity_small_strain.py _________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_elasticity_small_strain.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_elasticity_small_strain.py:3: in <module>\n    from sfepy import data_dir\nsfepy/__init__.py:3: in <module>\n    from .config import in_source_tree, top_dir, site_config\nsfepy/config.py:165: in <module>\n    site_config = Config()\nsfepy/config.py:64: in __init__\n    from sfepy.base.base import sfepy_config_dir\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n___________________ ERROR collecting sfepy/tests/test_fem.py ___________________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_fem.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_fem.py:4: in <module>\n    import sfepy.base.testing as tst\nsfepy/base/testing.py:7: in <module>\n    from sfepy.base.base import Struct, assert_, IndexedStruct\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n________________ ERROR collecting sfepy/tests/test_functions.py ________________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_functions.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_functions.py:4: in <module>\n    from sfepy import data_dir\nsfepy/__init__.py:3: in <module>\n    from .config import in_source_tree, top_dir, site_config\nsfepy/config.py:165: in <module>\n    site_config = Config()\nsfepy/config.py:64: in __init__\n    from sfepy.base.base import sfepy_config_dir\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n_______________ ERROR collecting sfepy/tests/test_high_level.py ________________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_high_level.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_high_level.py:5: in <module>\n    import sfepy.base.testing as tst\nsfepy/base/testing.py:7: in <module>\n    from sfepy.base.base import Struct, assert_, IndexedStruct\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n__________ ERROR collecting sfepy/tests/test_homogenization_engine.py __________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_homogenization_engine.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_homogenization_engine.py:3: in <module>\n    from sfepy.homogenization.engine import HomogenizationEngine as he\nsfepy/__init__.py:3: in <module>\n    from .config import in_source_tree, top_dir, site_config\nsfepy/config.py:165: in <module>\n    site_config = Config()\nsfepy/config.py:64: in __init__\n    from sfepy.base.base import sfepy_config_dir\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n________ ERROR collecting sfepy/tests/test_homogenization_perfusion.py _________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_homogenization_perfusion.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_homogenization_perfusion.py:3: in <module>\n    import sfepy.base.testing as tst\nsfepy/base/testing.py:7: in <module>\n    from sfepy.base.base import Struct, assert_, IndexedStruct\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n____________ ERROR collecting sfepy/tests/test_hyperelastic_tlul.py ____________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_hyperelastic_tlul.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_hyperelastic_tlul.py:3: in <module>\n    import sfepy.base.testing as tst\nsfepy/base/testing.py:7: in <module>\n    from sfepy.base.base import Struct, assert_, IndexedStruct\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n___________________ ERROR collecting sfepy/tests/test_io.py ____________________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_io.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_io.py:3: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n____________ ERROR collecting sfepy/tests/test_laplace_unit_disk.py ____________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_laplace_unit_disk.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_laplace_unit_disk.py:3: in <module>\n    from sfepy import data_dir\nsfepy/__init__.py:3: in <module>\n    from .config import in_source_tree, top_dir, site_config\nsfepy/config.py:165: in <module>\n    site_config = Config()\nsfepy/config.py:64: in __init__\n    from sfepy.base.base import sfepy_config_dir\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n___________ ERROR collecting sfepy/tests/test_laplace_unit_square.py ___________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_laplace_unit_square.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_laplace_unit_square.py:3: in <module>\n    from sfepy import data_dir\nsfepy/__init__.py:3: in <module>\n    from .config import in_source_tree, top_dir, site_config\nsfepy/config.py:165: in <module>\n    site_config = Config()\nsfepy/config.py:64: in __init__\n    from sfepy.base.base import sfepy_config_dir\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n__________________ ERROR collecting sfepy/tests/test_lcbcs.py __________________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_lcbcs.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_lcbcs.py:5: in <module>\n    import sfepy.base.testing as tst\nsfepy/base/testing.py:7: in <module>\n    from sfepy.base.base import Struct, assert_, IndexedStruct\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n_________________ ERROR collecting sfepy/tests/test_linalg.py __________________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_linalg.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_linalg.py:1: in <module>\n    import sfepy.base.testing as tst\nsfepy/base/testing.py:7: in <module>\n    from sfepy.base.base import Struct, assert_, IndexedStruct\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n_____________ ERROR collecting sfepy/tests/test_linear_solvers.py ______________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_linear_solvers.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_linear_solvers.py:3: in <module>\n    from sfepy import data_dir\nsfepy/__init__.py:3: in <module>\n    from .config import in_source_tree, top_dir, site_config\nsfepy/config.py:165: in <module>\n    site_config = Config()\nsfepy/config.py:64: in __init__\n    from sfepy.base.base import sfepy_config_dir\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n______________ ERROR collecting sfepy/tests/test_linearization.py ______________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_linearization.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_linearization.py:4: in <module>\n    import sfepy.base.testing as tst\nsfepy/base/testing.py:7: in <module>\n    from sfepy.base.base import Struct, assert_, IndexedStruct\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n___________________ ERROR collecting sfepy/tests/test_log.py ___________________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_log.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_log.py:5: in <module>\n    import sfepy.base.testing as tst\nsfepy/base/testing.py:7: in <module>\n    from sfepy.base.base import Struct, assert_, IndexedStruct\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n________________ ERROR collecting sfepy/tests/test_matcoefs.py _________________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_matcoefs.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_matcoefs.py:1: in <module>\n    import sfepy.base.testing as tst\nsfepy/base/testing.py:7: in <module>\n    from sfepy.base.base import Struct, assert_, IndexedStruct\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n_____________ ERROR collecting sfepy/tests/test_mesh_generators.py _____________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_mesh_generators.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_mesh_generators.py:4: in <module>\n    import sfepy.base.testing as tst\nsfepy/base/testing.py:7: in <module>\n    from sfepy.base.base import Struct, assert_, IndexedStruct\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n_______________ ERROR collecting sfepy/tests/test_mesh_interp.py _______________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_mesh_interp.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_mesh_interp.py:5: in <module>\n    from sfepy.base.conf import transform_variables\nsfepy/base/conf.py:14: in <module>\n    from sfepy.base.base import (Struct, IndexedStruct, dict_to_struct,\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n_____________ ERROR collecting sfepy/tests/test_mesh_smoothing.py ______________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_mesh_smoothing.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_mesh_smoothing.py:3: in <module>\n    import sfepy.base.testing as tst\nsfepy/base/testing.py:7: in <module>\n    from sfepy.base.base import Struct, assert_, IndexedStruct\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n_________________ ERROR collecting sfepy/tests/test_meshio.py __________________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_meshio.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_meshio.py:5: in <module>\n    from sfepy import data_dir\nsfepy/__init__.py:3: in <module>\n    from .config import in_source_tree, top_dir, site_config\nsfepy/config.py:165: in <module>\n    site_config = Config()\nsfepy/config.py:64: in __init__\n    from sfepy.base.base import sfepy_config_dir\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n_______________ ERROR collecting sfepy/tests/test_msm_laplace.py _______________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_msm_laplace.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_msm_laplace.py:4: in <module>\n    from sfepy.base.base import assert_\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n______________ ERROR collecting sfepy/tests/test_msm_symbolic.py _______________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_msm_symbolic.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_msm_symbolic.py:9: in <module>\n    from sfepy import data_dir\nsfepy/__init__.py:3: in <module>\n    from .config import in_source_tree, top_dir, site_config\nsfepy/config.py:165: in <module>\n    site_config = Config()\nsfepy/config.py:64: in __init__\n    from sfepy.base.base import sfepy_config_dir\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n_________________ ERROR collecting sfepy/tests/test_normals.py _________________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_normals.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_normals.py:3: in <module>\n    import sfepy.base.testing as tst\nsfepy/base/testing.py:7: in <module>\n    from sfepy.base.base import Struct, assert_, IndexedStruct\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n_________________ ERROR collecting sfepy/tests/test_parsing.py _________________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_parsing.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_parsing.py:1: in <module>\n    import sfepy.base.testing as tst\nsfepy/base/testing.py:7: in <module>\n    from sfepy.base.base import Struct, assert_, IndexedStruct\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n_______________ ERROR collecting sfepy/tests/test_poly_spaces.py _______________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_poly_spaces.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_poly_spaces.py:23: in <module>\n    from sfepy.base.base import assert_\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n_______________ ERROR collecting sfepy/tests/test_projections.py _______________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_projections.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_projections.py:5: in <module>\n    import sfepy\nsfepy/__init__.py:3: in <module>\n    from .config import in_source_tree, top_dir, site_config\nsfepy/config.py:165: in <module>\n    site_config = Config()\nsfepy/config.py:64: in __init__\n    from sfepy.base.base import sfepy_config_dir\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n_______________ ERROR collecting sfepy/tests/test_quadratures.py _______________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_quadratures.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_quadratures.py:10: in <module>\n    from sfepy.base.base import assert_, ordered_iteritems\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n________________ ERROR collecting sfepy/tests/test_ref_coors.py ________________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_ref_coors.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_ref_coors.py:5: in <module>\n    import sfepy\nsfepy/__init__.py:3: in <module>\n    from .config import in_source_tree, top_dir, site_config\nsfepy/config.py:165: in <module>\n    site_config = Config()\nsfepy/config.py:64: in __init__\n    from sfepy.base.base import sfepy_config_dir\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n_____________ ERROR collecting sfepy/tests/test_refine_hanging.py ______________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_refine_hanging.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_refine_hanging.py:9: in <module>\n    from sfepy.base.base import assert_, Struct\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n_________________ ERROR collecting sfepy/tests/test_regions.py _________________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_regions.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_regions.py:4: in <module>\n    from sfepy.base.conf import transform_functions\nsfepy/base/conf.py:14: in <module>\n    from sfepy.base.base import (Struct, IndexedStruct, dict_to_struct,\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n____________ ERROR collecting sfepy/tests/test_semismooth_newton.py ____________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_semismooth_newton.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_semismooth_newton.py:1: in <module>\n    import sympy as sm\nE   ModuleNotFoundError: No module named 'sympy'\n_________________ ERROR collecting sfepy/tests/test_sparse.py __________________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_sparse.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_sparse.py:1: in <module>\n    import sfepy.base.testing as tst\nsfepy/base/testing.py:7: in <module>\n    from sfepy.base.base import Struct, assert_, IndexedStruct\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n________________ ERROR collecting sfepy/tests/test_splinebox.py ________________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_splinebox.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_splinebox.py:2: in <module>\n    from sfepy import data_dir\nsfepy/__init__.py:3: in <module>\n    from .config import in_source_tree, top_dir, site_config\nsfepy/config.py:165: in <module>\n    site_config = Config()\nsfepy/config.py:64: in __init__\n    from sfepy.base.base import sfepy_config_dir\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n_________________ ERROR collecting sfepy/tests/test_tensors.py _________________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_tensors.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_tensors.py:1: in <module>\n    import sfepy.base.testing as tst\nsfepy/base/testing.py:7: in <module>\n    from sfepy.base.base import Struct, assert_, IndexedStruct\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n_____________ ERROR collecting sfepy/tests/test_term_call_modes.py _____________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_term_call_modes.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_term_call_modes.py:6: in <module>\n    from sfepy.base.base import ordered_iteritems\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n____________ ERROR collecting sfepy/tests/test_term_consistency.py _____________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_term_consistency.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_term_consistency.py:3: in <module>\n    from sfepy import data_dir\nsfepy/__init__.py:3: in <module>\n    from .config import in_source_tree, top_dir, site_config\nsfepy/config.py:165: in <module>\n    site_config = Config()\nsfepy/config.py:64: in __init__\n    from sfepy.base.base import sfepy_config_dir\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n____________ ERROR collecting sfepy/tests/test_term_sensitivity.py _____________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_term_sensitivity.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_term_sensitivity.py:5: in <module>\n    from sfepy.mechanics.matcoefs import stiffness_from_youngpoisson\nsfepy/__init__.py:3: in <module>\n    from .config import in_source_tree, top_dir, site_config\nsfepy/config.py:165: in <module>\n    site_config = Config()\nsfepy/config.py:64: in __init__\n    from sfepy.base.base import sfepy_config_dir\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n__________________ ERROR collecting sfepy/tests/test_units.py __________________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_units.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_units.py:1: in <module>\n    from sfepy.base.base import assert_\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n_________________ ERROR collecting sfepy/tests/test_volume.py __________________\nImportError while importing test module '/app/repo_to_process/sfepy/tests/test_volume.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nsfepy/tests/test_volume.py:7: in <module>\n    from sfepy import data_dir\nsfepy/__init__.py:3: in <module>\n    from .config import in_source_tree, top_dir, site_config\nsfepy/config.py:165: in <module>\n    site_config = Config()\nsfepy/config.py:64: in __init__\n    from sfepy.base.base import sfepy_config_dir\nsfepy/base/base.py:10: in <module>\n    import scipy.sparse as sp\nE   ModuleNotFoundError: No module named 'scipy'\n=========================== short test summary info ============================\nERROR sfepy/scripts/test_install.py\nERROR sfepy/tests/test_assembling.py\nERROR sfepy/tests/test_base.py\nERROR sfepy/tests/test_cmesh.py\nERROR sfepy/tests/test_conditions.py\nERROR sfepy/tests/test_declarative_examples.py\nERROR sfepy/tests/test_dg_field.py\nERROR sfepy/tests/test_dg_terms_calls.py\nERROR sfepy/tests/test_domain.py\nERROR sfepy/tests/test_ed_solvers.py\nERROR sfepy/tests/test_eigenvalue_solvers.py\nERROR sfepy/tests/test_elasticity_small_strain.py\nERROR sfepy/tests/test_fem.py\nERROR sfepy/tests/test_functions.py\nERROR sfepy/tests/test_high_level.py\nERROR sfepy/tests/test_homogenization_engine.py\nERROR sfepy/tests/test_homogenization_perfusion.py\nERROR sfepy/tests/test_hyperelastic_tlul.py\nERROR sfepy/tests/test_io.py\nERROR sfepy/tests/test_laplace_unit_disk.py\nERROR sfepy/tests/test_laplace_unit_square.py\nERROR sfepy/tests/test_lcbcs.py\nERROR sfepy/tests/test_linalg.py\nERROR sfepy/tests/test_linear_solvers.py\nERROR sfepy/tests/test_linearization.py\nERROR sfepy/tests/test_log.py\nERROR sfepy/tests/test_matcoefs.py\nERROR sfepy/tests/test_mesh_generators.py\nERROR sfepy/tests/test_mesh_interp.py\nERROR sfepy/tests/test_mesh_smoothing.py\nERROR sfepy/tests/test_meshio.py\nERROR sfepy/tests/test_msm_laplace.py\nERROR sfepy/tests/test_msm_symbolic.py\nERROR sfepy/tests/test_normals.py\nERROR sfepy/tests/test_parsing.py\nERROR sfepy/tests/test_poly_spaces.py\nERROR sfepy/tests/test_projections.py\nERROR sfepy/tests/test_quadratures.py\nERROR sfepy/tests/test_ref_coors.py\nERROR sfepy/tests/test_refine_hanging.py\nERROR sfepy/tests/test_regions.py\nERROR sfepy/tests/test_semismooth_newton.py\nERROR sfepy/tests/test_sparse.py\nERROR sfepy/tests/test_splinebox.py\nERROR sfepy/tests/test_tensors.py\nERROR sfepy/tests/test_term_call_modes.py\nERROR sfepy/tests/test_term_consistency.py\nERROR sfepy/tests/test_term_sensitivity.py\nERROR sfepy/tests/test_units.py\nERROR sfepy/tests/test_volume.py\n!!!!!!!!!!!!!!!!!!! Interrupted: 50 errors during collection !!!!!!!!!!!!!!!!!!!\n============================== 50 errors in 1.84s ==============================\n",
    "stderr": "",
    "execution_time": 2.0490951538085938
  }
]