[
  {
    "command": "pip install -e .",
    "success": false,
    "stdout": "Looking in indexes: https://repo.huaweicloud.com/repository/pypi/simple/\nObtaining file:///app/repo_to_process\n  Installing build dependencies: started\n  Installing build dependencies: finished with status 'done'\n  Checking if build backend supports build_editable: started\n  Checking if build backend supports build_editable: finished with status 'done'\n  Getting requirements to build editable: started\n  Getting requirements to build editable: finished with status 'done'\n  Preparing editable metadata (pyproject.toml): started\n  Preparing editable metadata (pyproject.toml): finished with status 'done'\nBuilding wheels for collected packages: pysam\n  Building editable for pysam (pyproject.toml): started\n  Building editable for pysam (pyproject.toml): finished with status 'error'\nFailed to build pysam\n",
    "stderr": "  error: subprocess-exited-with-error\n  \n  × Building editable for pysam (pyproject.toml) did not run successfully.\n  │ exit code: 1\n  ╰─> [158 lines of output]\n      # pysam: Cython 3.1.2 is available - using cythonize if necessary\n      # pysam: htslib mode is shared\n      # pysam: HTSLIB_CONFIGURE_OPTIONS=None\n      # pysam: (sysconfig) CC=x86_64-linux-gnu-gcc\n      # pysam: (sysconfig) CFLAGS=-Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g       -fstack-protector-strong -Wformat -Werror=format-security  -g -fwrapv -O2    -fPIC\n      # pysam: (sysconfig) LDFLAGS=-Wl,-Bsymbolic-functions      -g -fwrapv -O2\n      /bin/sh: 1: ./configure: not found\n      /bin/sh: 1: ./configure: not found\n      make: ./version.sh: No such file or directory\n      /tmp/pip-build-env-lu4v6zx3/overlay/local/lib/python3.10/dist-packages/setuptools/config/_apply_pyprojecttoml.py:82: SetuptoolsDeprecationWarning: `project.license` as a TOML table is deprecated\n      !!\n      \n              ********************************************************************************\n              Please use a simple string containing a SPDX expression for `project.license`. You can also use `project.license-files`. (Both options available on setuptools>=77.0.0).\n      \n              By 2026-Feb-18, you need to update your project and remove deprecated calls\n              or your builds will no longer be supported.\n      \n              See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.\n              ********************************************************************************\n      \n      !!\n        corresp(dist, value, root_dir)\n      /tmp/pip-build-env-lu4v6zx3/overlay/local/lib/python3.10/dist-packages/setuptools/config/_apply_pyprojecttoml.py:61: SetuptoolsDeprecationWarning: License classifiers are deprecated.\n      !!\n      \n              ********************************************************************************\n              Please consider removing the following classifiers in favor of a SPDX license expression:\n      \n              License :: OSI Approved\n      \n              See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.\n              ********************************************************************************\n      \n      !!\n        dist._finalize_license_expression()\n      /tmp/pip-build-env-lu4v6zx3/overlay/local/lib/python3.10/dist-packages/setuptools/dist.py:759: SetuptoolsDeprecationWarning: License classifiers are deprecated.\n      !!\n      \n              ********************************************************************************\n              Please consider removing the following classifiers in favor of a SPDX license expression:\n      \n              License :: OSI Approved\n      \n              See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.\n              ********************************************************************************\n      \n      !!\n        self._finalize_license_expression()\n      # pysam: htslib configure options: None\n      # pysam: htslib_config HTS_CFLAGS_AVX2=\n      # pysam: htslib_config HTS_CFLAGS_AVX512=\n      # pysam: htslib_config HTS_CFLAGS_SSE4=\n      # pysam: htslib_config LIBHTS_OBJS=kfunc.o kstring.o bcf_sr_sort.o bgzf.o errmod.o faidx.o header.o hfile.o hts.o hts_expr.o hts_os.o md5.o multipart.o probaln.o realn.o regidx.o region.o sam.o sam_mods.o simd.o synced_bcf_reader.o vcf_sweep.o tbx.o textutils.o thread_pool.o vcf.o vcfutils.o cram/cram_codecs.o cram/cram_decode.o cram/cram_encode.o cram/cram_external.o cram/cram_index.o cram/cram_io.o cram/cram_stats.o cram/mFILE.o cram/open_trace_file.o cram/pooled_alloc.o cram/string_alloc.o hfile_libcurl.o\n      # pysam: htslib_config LIBS=-lz -lm -lbz2 -llzma -lcurl\n      # pysam: htslib_config PLATFORM=Linux\n      # pysam: config_option: ENABLE_GCS=0\n      # pysam: config_option: ENABLE_PLUGINS=0\n      # pysam: config_option: ENABLE_S3=0\n      # pysam: config_option: HAVE_COMMONCRYPTO=0\n      # pysam: config_option: HAVE_HMAC=0\n      # pysam: config_option: HAVE_LIBBZ2=0\n      # pysam: config_option: HAVE_LIBCURL=0\n      # pysam: config_option: HAVE_LIBDEFLATE=0\n      # pysam: config_option: HAVE_LIBLZMA=0\n      # pysam: config_option: HAVE_MMAP=0\n      running editable_wheel\n      creating /tmp/pip-wheel-vnu5yalt/.tmp-uuz6zi7y/pysam.egg-info\n      writing /tmp/pip-wheel-vnu5yalt/.tmp-uuz6zi7y/pysam.egg-info/PKG-INFO\n      writing dependency_links to /tmp/pip-wheel-vnu5yalt/.tmp-uuz6zi7y/pysam.egg-info/dependency_links.txt\n      writing top-level names to /tmp/pip-wheel-vnu5yalt/.tmp-uuz6zi7y/pysam.egg-info/top_level.txt\n      writing manifest file '/tmp/pip-wheel-vnu5yalt/.tmp-uuz6zi7y/pysam.egg-info/SOURCES.txt'\n      reading manifest file '/tmp/pip-wheel-vnu5yalt/.tmp-uuz6zi7y/pysam.egg-info/SOURCES.txt'\n      reading manifest template 'MANIFEST.in'\n      warning: no files found matching 'KNOWN_BUGS'\n      warning: no files found matching 'THANKS'\n      warning: no files found matching 'pysam/libc*.c'\n      warning: no previously-included files found matching 'htslib/config.mk'\n      warning: no previously-included files found matching 'htslib/htscodecs.mk'\n      adding license file 'COPYING'\n      adding license file 'AUTHORS'\n      writing manifest file '/tmp/pip-wheel-vnu5yalt/.tmp-uuz6zi7y/pysam.egg-info/SOURCES.txt'\n      creating '/tmp/pip-wheel-vnu5yalt/.tmp-uuz6zi7y/pysam-0.23.3.dist-info'\n      creating /tmp/pip-wheel-vnu5yalt/.tmp-uuz6zi7y/pysam-0.23.3.dist-info/WHEEL\n      running build_py\n      running build_ext\n      checking for x86_64-linux-gnu-gcc option to enable C99 features...\n      creating /tmp/tmpi40t2ju4.build-temp/pysam\n      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/include/python3.10 -c pysam/conftest_cstd.c -o /tmp/tmpi40t2ju4.build-temp/pysam/conftest_cstd.o\n      x86_64-linux-gnu-gcc option to enable C99 features: none needed\n      creating htslib/config_vars.h for 'pysam.libchtslib' extension\n      building 'libhts.a'\n      make: ./version.sh: No such file or directory\n      gcc -g -Wall -O2 -fvisibility=hidden  -I. -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement   -c -o kfunc.o kfunc.c\n      gcc -g -Wall -O2 -fvisibility=hidden  -I. -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement   -c -o kstring.o kstring.c\n      gcc -g -Wall -O2 -fvisibility=hidden  -I. -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement   -c -o bcf_sr_sort.o bcf_sr_sort.c\n      gcc -g -Wall -O2 -fvisibility=hidden  -I. -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement   -c -o bgzf.o bgzf.c\n      bgzf.c:38:10: fatal error: zlib.h: No such file or directory\n         38 | #include <zlib.h>\n            |          ^~~~~~~~\n      compilation terminated.\n      make: *** [Makefile:187: bgzf.o] Error 1\n      Traceback (most recent call last):\n        File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 389, in <module>\n          main()\n        File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 373, in main\n          json_out[\"return_val\"] = hook(**hook_input[\"kwargs\"])\n        File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 303, in build_editable\n          return hook(wheel_directory, config_settings, metadata_directory)\n        File \"/tmp/pip-build-env-lu4v6zx3/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py\", line 468, in build_editable\n          return self._build_with_temp_dir(\n        File \"/tmp/pip-build-env-lu4v6zx3/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py\", line 404, in _build_with_temp_dir\n          self.run_setup()\n        File \"/tmp/pip-build-env-lu4v6zx3/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py\", line 512, in run_setup\n          super().run_setup(setup_script=setup_script)\n        File \"/tmp/pip-build-env-lu4v6zx3/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py\", line 317, in run_setup\n          exec(code, locals())\n        File \"<string>\", line 722, in <module>\n        File \"/tmp/pip-build-env-lu4v6zx3/overlay/local/lib/python3.10/dist-packages/setuptools/__init__.py\", line 115, in setup\n          return distutils.core.setup(**attrs)\n        File \"/tmp/pip-build-env-lu4v6zx3/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py\", line 186, in setup\n          return run_commands(dist)\n        File \"/tmp/pip-build-env-lu4v6zx3/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py\", line 202, in run_commands\n          dist.run_commands()\n        File \"/tmp/pip-build-env-lu4v6zx3/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py\", line 1002, in run_commands\n          self.run_command(cmd)\n        File \"/tmp/pip-build-env-lu4v6zx3/overlay/local/lib/python3.10/dist-packages/setuptools/dist.py\", line 1102, in run_command\n          super().run_command(command)\n        File \"/tmp/pip-build-env-lu4v6zx3/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py\", line 1021, in run_command\n          cmd_obj.run()\n        File \"/tmp/pip-build-env-lu4v6zx3/overlay/local/lib/python3.10/dist-packages/setuptools/command/editable_wheel.py\", line 139, in run\n          self._create_wheel_file(bdist_wheel)\n        File \"/tmp/pip-build-env-lu4v6zx3/overlay/local/lib/python3.10/dist-packages/setuptools/command/editable_wheel.py\", line 349, in _create_wheel_file\n          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)\n        File \"/tmp/pip-build-env-lu4v6zx3/overlay/local/lib/python3.10/dist-packages/setuptools/command/editable_wheel.py\", line 272, in _run_build_commands\n          self._run_build_subcommands()\n        File \"/tmp/pip-build-env-lu4v6zx3/overlay/local/lib/python3.10/dist-packages/setuptools/command/editable_wheel.py\", line 299, in _run_build_subcommands\n          self.run_command(name)\n        File \"/tmp/pip-build-env-lu4v6zx3/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py\", line 357, in run_command\n          self.distribution.run_command(command)\n        File \"/tmp/pip-build-env-lu4v6zx3/overlay/local/lib/python3.10/dist-packages/setuptools/dist.py\", line 1102, in run_command\n          super().run_command(command)\n        File \"/tmp/pip-build-env-lu4v6zx3/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py\", line 1021, in run_command\n          cmd_obj.run()\n        File \"<string>\", line 299, in run\n        File \"/tmp/pip-build-env-lu4v6zx3/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/command/build_ext.py\", line 368, in run\n          self.build_extensions()\n        File \"<string>\", line 319, in build_extensions\n        File \"/tmp/pip-build-env-lu4v6zx3/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/command/build_ext.py\", line 484, in build_extensions\n          self._build_extensions_serial()\n        File \"/tmp/pip-build-env-lu4v6zx3/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/command/build_ext.py\", line 510, in _build_extensions_serial\n          self.build_extension(ext)\n        File \"<string>\", line 354, in build_extension\n        File \"<string>\", line 607, in prebuild_libchtslib\n        File \"<string>\", line 77, in run_make\n        File \"/usr/lib/python3.10/subprocess.py\", line 369, in check_call\n          raise CalledProcessError(retcode, cmd)\n      subprocess.CalledProcessError: Command '['make', 'ALL_CPPFLAGS=-I. -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement  $(CPPFLAGS)', 'lib-static']' returned non-zero exit status 2.\n      [end of output]\n  \n  note: This error originates from a subprocess, and is likely not a problem with pip.\n  ERROR: Failed building editable for pysam\nerror: failed-wheel-build-for-install\n\n× Failed to build installable wheels for some pyproject.toml based projects\n╰─> pysam\n",
    "execution_time": 4.392691612243652
  },
  {
    "command": "pytest",
    "success": false,
    "stdout": "============================= test session starts ==============================\nplatform linux -- Python 3.10.12, pytest-8.4.1, pluggy-1.6.0 -- /usr/bin/python3\ncachedir: .pytest_cache\nrootdir: /app/repo_to_process\nconfigfile: setup.cfg\ntestpaths: pysam, tests\ncollecting ... collected 0 items / 15 errors\n\n==================================== ERRORS ====================================\n________________ ERROR collecting tests/AlignedSegment_test.py _________________\nImportError while importing test module '/app/repo_to_process/tests/AlignedSegment_test.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests/AlignedSegment_test.py:2: in <module>\n    import pysam\nE   ModuleNotFoundError: No module named 'pysam'\n______________ ERROR collecting tests/AlignmentFileHeader_test.py ______________\nImportError while importing test module '/app/repo_to_process/tests/AlignmentFileHeader_test.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests/AlignmentFileHeader_test.py:13: in <module>\n    import pysam\nE   ModuleNotFoundError: No module named 'pysam'\n______________ ERROR collecting tests/AlignmentFilePileup_test.py ______________\nImportError while importing test module '/app/repo_to_process/tests/AlignmentFilePileup_test.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests/AlignmentFilePileup_test.py:3: in <module>\n    import pysam\nE   ModuleNotFoundError: No module named 'pysam'\n_________________ ERROR collecting tests/AlignmentFile_test.py _________________\nImportError while importing test module '/app/repo_to_process/tests/AlignmentFile_test.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests/AlignmentFile_test.py:20: in <module>\n    import pysam\nE   ModuleNotFoundError: No module named 'pysam'\n_____________ ERROR collecting tests/StreamFiledescriptors_test.py _____________\nImportError while importing test module '/app/repo_to_process/tests/StreamFiledescriptors_test.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests/StreamFiledescriptors_test.py:6: in <module>\n    from pysam import AlignmentFile\nE   ModuleNotFoundError: No module named 'pysam'\n__________________ ERROR collecting tests/VariantFile_test.py __________________\nImportError while importing test module '/app/repo_to_process/tests/VariantFile_test.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests/VariantFile_test.py:6: in <module>\n    import pysam\nE   ModuleNotFoundError: No module named 'pysam'\n_________________ ERROR collecting tests/VariantRecord_test.py _________________\nImportError while importing test module '/app/repo_to_process/tests/VariantRecord_test.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests/VariantRecord_test.py:1: in <module>\n    import pysam\nE   ModuleNotFoundError: No module named 'pysam'\n____________________ ERROR collecting tests/compile_test.py ____________________\nImportError while importing test module '/app/repo_to_process/tests/compile_test.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests/compile_test.py:12: in <module>\n    import pysam\nE   ModuleNotFoundError: No module named 'pysam'\n_____________________ ERROR collecting tests/faidx_test.py _____________________\nImportError while importing test module '/app/repo_to_process/tests/faidx_test.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests/faidx_test.py:1: in <module>\n    import pysam\nE   ModuleNotFoundError: No module named 'pysam'\n____________________ ERROR collecting tests/linking_test.py ____________________\nImportError while importing test module '/app/repo_to_process/tests/linking_test.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests/linking_test.py:7: in <module>\n    import pysam\nE   ModuleNotFoundError: No module named 'pysam'\n___________________ ERROR collecting tests/samtools_test.py ____________________\nImportError while importing test module '/app/repo_to_process/tests/samtools_test.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests/samtools_test.py:16: in <module>\n    import pysam\nE   ModuleNotFoundError: No module named 'pysam'\n_____________________ ERROR collecting tests/tabix_test.py _____________________\nImportError while importing test module '/app/repo_to_process/tests/tabix_test.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests/tabix_test.py:11: in <module>\n    import pysam\nE   ModuleNotFoundError: No module named 'pysam'\n_________________ ERROR collecting tests/tabixproxies_test.py __________________\nImportError while importing test module '/app/repo_to_process/tests/tabixproxies_test.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests/tabixproxies_test.py:2: in <module>\n    import pysam\nE   ModuleNotFoundError: No module named 'pysam'\n________________ ERROR collecting tests/test_samtools_python.py ________________\nImportError while importing test module '/app/repo_to_process/tests/test_samtools_python.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests/test_samtools_python.py:1: in <module>\n    import pysam\nE   ModuleNotFoundError: No module named 'pysam'\n_________________ ERROR collecting tests/typechecking_test.py __________________\nImportError while importing test module '/app/repo_to_process/tests/typechecking_test.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests/typechecking_test.py:7: in <module>\n    import pysam\nE   ModuleNotFoundError: No module named 'pysam'\n=========================== short test summary info ============================\nERROR tests/AlignedSegment_test.py\nERROR tests/AlignmentFileHeader_test.py\nERROR tests/AlignmentFilePileup_test.py\nERROR tests/AlignmentFile_test.py\nERROR tests/StreamFiledescriptors_test.py\nERROR tests/VariantFile_test.py\nERROR tests/VariantRecord_test.py\nERROR tests/compile_test.py\nERROR tests/faidx_test.py\nERROR tests/linking_test.py\nERROR tests/samtools_test.py\nERROR tests/tabix_test.py\nERROR tests/tabixproxies_test.py\nERROR tests/test_samtools_python.py\nERROR tests/typechecking_test.py\n!!!!!!!!!!!!!!!!!!! Interrupted: 15 errors during collection !!!!!!!!!!!!!!!!!!!\n============================== 15 errors in 0.32s ==============================\n",
    "stderr": "",
    "execution_time": 0.5122129917144775
  }
]